<?php

namespace App\Modules\Inventory\Services;

use App\Modules\Inventory\Models\InventoryBatch;
use App\Modules\Inventory\Models\Product;
use Illuminate\Support\Carbon;
use LogicException;

class AutoBatchNumberService
{
    private const BATCH_NUMBER_MAX_LENGTH = 100;

    /**
     * @param  array<string, mixed>  $item
     */
    public static function isAutoBatchRequest(array $item): bool
    {
        if (($item['batch_mode'] ?? null) === 'existing' || filled($item['inventory_batch_id'] ?? null)) {
            return false;
        }

        if (array_key_exists('auto_batch', $item)) {
            return filter_var($item['auto_batch'], FILTER_VALIDATE_BOOLEAN);
        }

        if (filled($item['batch_number'] ?? null)) {
            return false;
        }

        return true;
    }

    public function generateBatchNumber(int $branchId, Product $product, string $expiryDate): string
    {
        if (! $product->requires_batch_tracking) {
            throw new LogicException('Auto batch is only for batch-tracked products.');
        }

        $prefix = $this->buildPrefix($product, $expiryDate);

        $existingNumbers = InventoryBatch::query()
            ->forBranch($branchId)
            ->forProduct($product->id)
            ->where('batch_number', 'like', $prefix.'-%')
            ->lockForUpdate()
            ->pluck('batch_number');

        $maxSequence = 0;

        foreach ($existingNumbers as $batchNumber) {
            if (preg_match('/-(\d{3})$/', (string) $batchNumber, $matches) === 1) {
                $maxSequence = max($maxSequence, (int) $matches[1]);
            }
        }

        $candidate = sprintf('%s-%03d', $prefix, $maxSequence + 1);

        if (strlen($candidate) > self::BATCH_NUMBER_MAX_LENGTH) {
            throw new LogicException('Generated batch number exceeds schema length limit.');
        }

        return $candidate;
    }

    public function isAutoGeneratedBatchNumber(?string $batchNumber): bool
    {
        return is_string($batchNumber) && str_starts_with($batchNumber, 'AUTO-');
    }

    private function buildPrefix(Product $product, string $expiryDate): string
    {
        $code = $this->sanitizeProductCode($product);
        $expiryPart = Carbon::parse($expiryDate)->format('Ymd');

        return 'AUTO-'.$code.'-'.$expiryPart;
    }

    private function sanitizeProductCode(Product $product): string
    {
        $code = strtoupper(trim((string) ($product->code ?? '')));
        $code = preg_replace('/[^A-Z0-9-]+/', '-', $code) ?? '';
        $code = preg_replace('/-+/', '-', $code) ?? '';
        $code = trim($code, '-');

        if ($code === '') {
            return 'P'.$product->id;
        }

        $reservedLength = strlen('AUTO--YYYYMMDD-001');

        if (strlen($code) > self::BATCH_NUMBER_MAX_LENGTH - $reservedLength) {
            $code = substr($code, 0, self::BATCH_NUMBER_MAX_LENGTH - $reservedLength);
            $code = rtrim($code, '-');
        }

        return $code;
    }
}
