<?php

/**
 * DMO-2 application-level architecture rules.
 * Machine-readable governance — validated by architecture:dmo-governance-check.
 */
return [
    'sprint' => 'DMO-3',

    'rules' => [
        [
            'rule_id' => 'DMO-R001',
            'title' => 'Canonical metric uniqueness',
            'severity' => 'error',
            'description' => 'Every canonical metric must have exactly one canonical name.',
            'applies_to' => ['metrics', 'owner_kpis'],
            'validation' => 'canonical_metric_names_unique',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R002',
            'title' => 'Metric grain declaration',
            'severity' => 'error',
            'description' => 'Every metric must declare grain.',
            'applies_to' => ['metrics'],
            'validation' => 'metric_grain_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R003',
            'title' => 'Branch dimension for branch-scoped metrics',
            'severity' => 'error',
            'description' => 'Every branch-scoped metric must declare branch dimension/filter.',
            'applies_to' => ['metrics', 'owner_kpis'],
            'validation' => 'branch_dimension_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R004',
            'title' => 'Date dimension for time-based metrics',
            'severity' => 'error',
            'description' => 'Every time-based metric must declare date field/date dimension.',
            'applies_to' => ['metrics', 'owner_kpis'],
            'validation' => 'date_dimension_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R005',
            'title' => 'Financial metric status rules',
            'severity' => 'error',
            'description' => 'Every financial metric must declare invoice/payment/status rules.',
            'applies_to' => ['metrics', 'owner_kpis'],
            'validation' => 'financial_status_rules',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R006',
            'title' => 'Inventory stock ledger derivation',
            'severity' => 'error',
            'description' => 'Every inventory stock metric must be ledger-derived from inventory movements.',
            'applies_to' => ['metrics'],
            'validation' => 'inventory_ledger_derived',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R007',
            'title' => 'Receivable source specification',
            'severity' => 'error',
            'description' => 'Every receivable metric must specify derived or persisted source.',
            'applies_to' => ['metrics'],
            'validation' => 'receivable_source_specified',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R008',
            'title' => 'Clinical aggregate privacy',
            'severity' => 'error',
            'description' => 'Every clinical metric/report must avoid PHI/row-level clinical output.',
            'applies_to' => ['metrics', 'commands'],
            'validation' => 'clinical_phi_safe_output',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R009',
            'title' => 'Owner KPI canonical mapping',
            'severity' => 'error',
            'description' => 'Every Owner KPI must map to one canonical metric or one documented derived canonical KPI.',
            'applies_to' => ['owner_kpis'],
            'validation' => 'owner_kpi_canonical_mapping',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R010',
            'title' => 'Report metric entity mapping',
            'severity' => 'warning',
            'description' => 'Every report/export/dashboard metric must map to canonical entity and canonical metric.',
            'applies_to' => ['metrics', 'reports'],
            'validation' => 'report_entity_metric_mapping',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R011',
            'title' => 'Entity scope declaration',
            'severity' => 'error',
            'description' => 'Every canonical entity must declare scope: branch/global/system.',
            'applies_to' => ['entities'],
            'validation' => 'entity_scope_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R012',
            'title' => 'Sensitivity classification',
            'severity' => 'error',
            'description' => 'Every sensitive entity/metric must declare sensitivity classification.',
            'applies_to' => ['entities', 'metrics', 'owner_kpis'],
            'validation' => 'sensitivity_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R013',
            'title' => 'Blocked metrics not Owner KPIs',
            'severity' => 'error',
            'description' => 'Blocked metrics must not be used as canonical Owner KPI until resolved.',
            'applies_to' => ['owner_kpis', 'metrics'],
            'validation' => 'blocked_not_owner_kpi',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R014',
            'title' => 'Duplicate alias resolution',
            'severity' => 'error',
            'description' => 'Duplicate aliases must point to alias_of canonical KPI.',
            'applies_to' => ['owner_kpis', 'aliases'],
            'validation' => 'alias_points_to_canonical',
            'status' => 'active',
        ],
        [
            'rule_id' => 'DMO-R015',
            'title' => 'Registry change workflow',
            'severity' => 'info',
            'description' => 'Future metric changes must update registry, lineage, tests, and docs.',
            'applies_to' => ['process'],
            'validation' => 'registry_change_workflow',
            'status' => 'active',
        ],
    ],

    'deferred_warnings' => [],

    'resolved_metrics' => [
        'DMO-M001' => 'net_revenue defined via DmoMetricService — collected payments only',
        'DMO-M003' => 'receivable_aging_bucket computed at read time via DmoMetricService',
        'DMO-M006' => 'Treatment/tariff multi-branch boundary enforced via TariffBoundaryService',
        'DMO-M007' => 'pod_count from trx_lab_deliveries signature proof via DmoMetricService',
    ],
];
