<?php

/**
 * ROADMAP-1 — National Foundation Expansion Roadmap (source-locked).
 *
 * Canonical machine-readable roadmap consumed by:
 *  - App\Services\Architecture\FoundationRoadmapService (validation)
 *  - architecture:foundation-roadmap-check (governance command)
 *  - architecture:foundation-governance-summary (ROADMAP section)
 *
 * Companion doc: docs/architecture/national-foundation-expansion-roadmap.md
 *
 * RULES:
 *  - This file is the source of truth for foundation sequencing.
 *  - Future foundation sprints MUST follow `approved_sequence`.
 *  - Any change to order/scope requires an explicit ROADMAP update sprint + evidence doc.
 *  - This sprint (ROADMAP-1) only locks roadmap/sequencing/governance — no foundation
 *    feature is implemented here.
 */
return [
    'roadmap_id' => 'ROADMAP-1',
    'title' => 'National Foundation Expansion Roadmap Source Lock',
    'source_locked' => true,
    'active_track' => 'foundation_expansion',

    'current_baseline' => [
        'dq' => 'GO',
        'dq1' => 'GO',
        'dq2' => 'GO',
        'dq3' => 'GO',
        'dq3_1' => 'GO',
        'dmo' => 'GO',
        'nsf_raw' => 'GO',
        'nsf_effective' => 'GO',
        'combined_foundation' => 'GO',
        'node_runtime' => '>=20',
        'observability' => 'validated',
        'ci_evidence_gates' => 'automated',
        'baseline_sprint' => 'NSF-8',
    ],

    'principles' => [
        'foundation_before_feature_scale',
        'one_foundation_per_scoped_sprint',
        'readiness_or_design_first_for_risky_infra',
        'no_production_destructive_changes',
        'preserve_dq_dmo_nsf_combined_go',
        'every_sprint_updates_evidence_docs',
        'every_sprint_runs_test_pint_graphify',
        'every_deploy_backs_up_db_first',
        'every_production_deploy_runs_dq_dmo_nsf_foundation_gates',
    ],

    'rules' => [
        'future_sprints_must_follow_sequence' => true,
        'roadmap_change_requires_roadmap_update_sprint' => true,
        'preserve_foundation_go' => true,
        'rc_must_be_last' => true,
        'no_production_partitioning_in_part1' => true,
        'no_replica_read_routing_without_approval' => true,
        'no_lb_pilot_before_stateless_go' => true,
        // ENT-0 — Enterprise Foundation Freeze Rules & Roadmap Reconciliation.
        'enterprise_foundation_freeze_active' => true,
        'enterprise_freeze_rules_doc' => 'docs/architecture/enterprise-foundation-freeze-rules.md',
        // ENT-1 — Enterprise Architecture Baseline Lock.
        'enterprise_architecture_baseline_locked' => true,
        'enterprise_architecture_baseline_doc' => 'docs/architecture/enterprise-architecture-baseline-lock.md',
        // ENT-2 — Database Performance Contract.
        'database_performance_contract_locked' => true,
        'database_performance_contract_doc' => 'docs/architecture/database-performance-contract.md',
        // ENT-3 — Reporting Materialized Summary Expansion.
        'reporting_materialized_summary_contract_locked' => true,
        'reporting_materialized_summary_contract_doc' => 'docs/architecture/reporting-materialized-summary-contract.md',
        // ENT-4 — Redis Cache Enterprise Policy.
        'redis_cache_enterprise_policy_locked' => true,
        'redis_cache_enterprise_policy_doc' => 'docs/architecture/redis-cache-enterprise-policy.md',
        'cache_ttl_matrix_doc' => 'docs/architecture/cache-ttl-matrix.md',
        'cache_invalidation_matrix_doc' => 'docs/architecture/cache-invalidation-matrix.md',
        'redis_readiness_runbook_doc' => 'docs/architecture/redis-readiness-runbook.md',
        // ENT-5 — Queue, Retry & Failed Job Governance.
        'queue_retry_failed_job_governance_locked' => true,
        'queue_retry_failed_job_governance_doc' => 'docs/architecture/queue-retry-failed-job-governance.md',
        'queue_worker_operations_runbook_doc' => 'docs/architecture/queue-worker-operations-runbook.md',
        // ENT-6 — Idempotency & Outbox Foundation.
        'idempotency_outbox_governance_locked' => true,
        'idempotency_outbox_governance_doc' => 'docs/architecture/idempotency-outbox-foundation-governance.md',
        // ENT-7 — Developer Assistance Console.
        'developer_console_governance_locked' => true,
        'developer_console_governance_doc' => 'docs/architecture/developer-assistance-console-governance.md',
        // ENT-8 — Observability & Health Check Pack.
        'health_check_governance_locked' => true,
        'health_check_governance_doc' => 'docs/architecture/observability-health-check-pack-governance.md',
        // ENT-9 — Security & PII Compliance Hardening.
        'security_compliance_governance_locked' => true,
        'security_compliance_governance_doc' => 'docs/architecture/security-pii-compliance-hardening-governance.md',
        // ENT-10 — CI/CD Enterprise Gate.
        'cicd_enterprise_gate_governance_locked' => true,
        'cicd_enterprise_gate_governance_doc' => 'docs/architecture/cicd-enterprise-gate-governance.md',
        'deployment_rollback_governance_locked' => true,
        'deployment_rollback_governance_doc' => 'docs/architecture/deployment-rollback-automation-governance.md',
        // ENT-12 — Backup & Disaster Recovery Automation.
        'backup_dr_governance_locked' => true,
        'backup_dr_governance_doc' => 'docs/architecture/backup-disaster-recovery-automation-governance.md',
        // ENT-13 — Load Test 5 Cabang Baseline.
        'load_test_baseline_governance_locked' => true,
        'load_test_baseline_governance_doc' => 'docs/architecture/load-test-5-cabang-baseline-governance.md',
        // ENT-14 — Load Test Scale Projection.
        'load_test_scale_projection_governance_locked' => true,
        'load_test_scale_projection_governance_doc' => 'docs/architecture/load-test-scale-projection-governance.md',
        // ENT-15 — Enterprise Documentation & Runbook.
        'enterprise_documentation_governance_locked' => true,
        'enterprise_documentation_governance_doc' => 'docs/architecture/enterprise-documentation-runbook-governance.md',
    ],

    /**
     * Approved sprint sequence. `priority` = stable execution order (ascending).
     * The very last item (highest priority) must be the RC consolidation.
     */
    'approved_sequence' => [
        [
            'id' => 'NSF-9',
            'title' => 'Release Safety, Feature Flag & Automated Smoke',
            'status' => 'completed',
            'priority' => 1,
            'depends_on' => ['NSF-8'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Lock release safety by adding a governed feature-flag layer and an automated post-deploy smoke suite so every future foundation sprint can be rolled out behind a flag and verified automatically.',
            'why_this_order' => 'Feature flags and automated smoke must exist before any risky runtime feature (Redis, Queue, PgBouncer) so those can be flag-gated and smoke-verified.',
            'allowed_scope' => [
                'feature flag registry + resolver (config/db-backed, no external SaaS)',
                'automated smoke command/suite runnable locally and in CI/VPS',
                'documentation of rollout/rollback via flags',
            ],
            'out_of_scope' => [
                'enabling Redis/Queue/PgBouncer',
                'any destructive migration',
                'external feature-flag SaaS dependency',
            ],
            'production_safety_rule' => 'Flags default OFF; smoke is read-only and must not mutate financial/inventory data.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'feature flag layer present and default-off',
                'automated smoke suite green locally and in CI',
                'DQ/DMO/NSF/Combined remain GO',
            ],
            'watch_criteria' => [
                'smoke suite partial coverage documented as backlog',
                'flag registry present but rollback playbook incomplete',
            ],
            'no_go_criteria' => [
                'flags default ON',
                'smoke mutates production data',
                'foundation GO regressed',
            ],
            'deliverables' => [
                'feature flag config/service',
                'automated smoke command',
                'evidence doc',
            ],
        ],
        [
            'id' => 'NSF-10',
            'title' => 'Observability, Backup & Release Safety Hardening',
            'status' => 'completed',
            'priority' => 2,
            'depends_on' => ['NSF-9'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Harden observability, backup verification, and release-safety runbooks building on NSF-9 flags/smoke.',
            'why_this_order' => 'Observability and backup hardening must precede stateful infra (cache/queue/db tuning) so regressions are detectable and recoverable.',
            'allowed_scope' => [
                'backup verification runbook + restore drill doc',
                'observability metric/log coverage expansion (no PII)',
                'release safety checklist automation',
            ],
            'out_of_scope' => [
                'enabling caching/queue backends',
                'exposing PII/secrets in logs/metrics',
            ],
            'production_safety_rule' => 'Backups verified before any future stateful rollout; no secrets/PII in observability output.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'backup + restore drill documented and evidenced',
                'observability coverage expanded without PII',
                'foundation GO preserved',
            ],
            'watch_criteria' => ['restore drill deferred to next window with owner sign-off'],
            'no_go_criteria' => ['PII/secrets in logs', 'no verified backup path'],
            'deliverables' => ['backup verification runbook', 'observability hardening', 'evidence doc'],
        ],
        [
            'id' => 'CACHE-1',
            'title' => 'Cache Strategy, Redis Readiness & Invalidation Governance',
            'status' => 'completed',
            'priority' => 3,
            'depends_on' => ['NSF-9'],
            'category' => 'cache',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_invalidation_rules' => true,
            'disambiguation_note' => 'This is the earlier design-only cache strategy/invalidation-governance sprint (governance section: cache_governance). See CACHE-1-REDIS-READINESS (priority 12) for the later Redis shared cache/session runtime-readiness sprint (cache_redis_governance) — do not conflate the two.',
            'objective' => 'Define the cache strategy and Redis readiness with a mandatory invalidation governance model before any critical value is cached.',
            'why_this_order' => 'Cache readiness (with invalidation tests) is prerequisite for read-replica usefulness and comes after feature-flag/smoke so it can be flag-gated and verified.',
            'allowed_scope' => [
                'cache key taxonomy + TTL policy',
                'invalidation rules + tests for cached values',
                'Redis readiness/config design (not enabling critical caching)',
            ],
            'out_of_scope' => [
                'caching critical mutable financial/inventory values without invalidation tests',
                'making Redis a hard runtime dependency for core flows',
            ],
            'production_safety_rule' => 'No Redis cache for critical mutable financial/inventory values without invalidation tests.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'invalidation rules documented and tested',
                'cache taxonomy + TTL policy locked',
                'foundation GO preserved',
            ],
            'watch_criteria' => ['non-critical cache candidates deferred with backlog note'],
            'no_go_criteria' => [
                'critical financial/inventory value cached without invalidation test',
                'foundation GO regressed',
            ],
            'deliverables' => ['cache strategy doc', 'invalidation rules + tests', 'evidence doc'],
        ],
        [
            'id' => 'QUEUE-1',
            'title' => 'Queue, Idempotency & Outbox Foundation',
            'status' => 'completed',
            'priority' => 4,
            'depends_on' => ['NSF-9', 'CACHE-1'],
            'category' => 'queue',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_idempotency_rules' => true,
            'requires_outbox_rules' => true,
            'objective' => 'Establish the queue foundation with mandatory idempotency keys and an outbox pattern so async integrations are safe and replayable.',
            'why_this_order' => 'Queue/outbox must exist before any async integration; depends on cache readiness and feature-flag/smoke for safe rollout.',
            'allowed_scope' => [
                'queue design + idempotency key convention',
                'outbox table/design for reliable async dispatch',
                'retry/failure policy definition',
            ],
            'out_of_scope' => [
                'auto-sending WhatsApp',
                'auto-creating LabOrder from RME payment',
                'queue jobs without idempotency key or retry/failure policy',
            ],
            'production_safety_rule' => 'No queue job without idempotency key or retry/failure policy.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'idempotency key convention enforced',
                'outbox pattern documented + tested',
                'retry/failure policy defined',
            ],
            'watch_criteria' => ['outbox adopted for subset of integrations, remainder backlogged'],
            'no_go_criteria' => ['job without idempotency/retry policy', 'foundation GO regressed'],
            'deliverables' => ['queue+outbox design', 'idempotency convention', 'evidence doc'],
        ],
        [
            'id' => 'DBPERF-1',
            'title' => 'PostgreSQL Index Optimization & Query Plan Audit',
            'status' => 'completed',
            'priority' => 5,
            'depends_on' => ['NSF-9'],
            'category' => 'db_performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Audit query plans and optimize indexes with additive, non-destructive migrations before connection pooling/runtime tuning.',
            'why_this_order' => 'Index audit must precede PgBouncer/runtime tuning so pooling is applied to an already-optimized workload.',
            'allowed_scope' => [
                'EXPLAIN/query-plan audit',
                'additive index migrations (no drops/rewrites of hot tables in production without plan)',
                'slow-query documentation',
            ],
            'out_of_scope' => ['destructive schema rewrites', 'partitioning production migration'],
            'production_safety_rule' => 'Index changes are additive; no migrate:fresh/db:wipe; large index builds planned for low-traffic window.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['query plan audit documented', 'additive indexes validated', 'foundation GO preserved'],
            'watch_criteria' => ['some index candidates deferred to low-traffic window'],
            'no_go_criteria' => ['destructive schema change', 'foundation GO regressed'],
            'deliverables' => ['query plan audit', 'index migrations', 'evidence doc'],
        ],
        [
            'id' => 'DBPERF-2',
            'title' => 'PgBouncer & PostgreSQL Runtime Tuning',
            'status' => 'completed',
            'priority' => 6,
            'depends_on' => ['DBPERF-1'],
            'category' => 'db_performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_rollback_plan' => true,
            'objective' => 'Design PgBouncer connection pooling and PostgreSQL runtime tuning with an explicit connection-pool rollback plan.',
            'why_this_order' => 'Follows index audit so pooling/tuning target an optimized workload; readiness-first with rollback plan.',
            'allowed_scope' => [
                'PgBouncer pool sizing/mode design',
                'PostgreSQL runtime parameter tuning proposal',
                'connection-pool rollback plan',
            ],
            'out_of_scope' => ['production PgBouncer routing without rollback plan'],
            'production_safety_rule' => 'No PgBouncer production routing without connection pool rollback plan.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['pool design + rollback plan documented', 'tuning proposal evidenced', 'foundation GO preserved'],
            'watch_criteria' => ['pilot pooling on non-critical path only'],
            'no_go_criteria' => ['production routing without rollback plan', 'foundation GO regressed'],
            'deliverables' => ['PgBouncer design', 'runtime tuning proposal', 'rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'RPT-1',
            'title' => 'Materialized View + rpt_* Summary Foundation',
            'status' => 'completed',
            'priority' => 7,
            'depends_on' => ['DBPERF-2'],
            'category' => 'reporting',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Introduce rpt_* summary tables first, then materialized views, so reporting reads move off transactional tables safely.',
            'why_this_order' => 'rpt_* summary must precede materialized view expansion; follows index audit for efficient refresh.',
            'allowed_scope' => [
                'rpt_* summary table design + refresh strategy',
                'materialized view design/readiness (additive, evidence-based)',
                'feature-flag gated future read-path routing for reports',
            ],
            'out_of_scope' => ['destructive replacement of transactional tables', 'exposing KTP/NIK in summaries'],
            'production_safety_rule' => 'Additive rpt_* only; no KTP/NIK in summaries; refresh must not lock hot tables.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['rpt_* summary foundation documented + tested', 'materialized view design locked', 'foundation GO preserved'],
            'watch_criteria' => ['materialized view rollout phased'],
            'no_go_criteria' => ['PII in summaries', 'foundation GO regressed'],
            'deliverables' => ['rpt_* governance config', 'materialized view readiness policy', 'dry-run refresh command', 'evidence doc'],
        ],
        [
            'id' => 'STORAGE-1',
            'title' => 'Object Storage Readiness',
            'status' => 'completed',
            'priority' => 8,
            'depends_on' => ['NSF-10'],
            'category' => 'storage',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_rollback_plan' => true,
            'governance_section' => 'storage_governance',
            'readiness_command' => 'storage:object-readiness-check',
            'go_tag' => 'storage-1-object-storage-readiness-go',
            'go_commit' => 'd8a9c73',
            'objective' => 'Prepare object storage (S3-compatible) readiness for uploaded assets so the app can become stateless.',
            'why_this_order' => 'Object storage must precede stateless/load balancer because local-disk assets block horizontal scaling.',
            'allowed_scope' => [
                'object storage driver readiness/config design',
                'asset migration plan with local backup + rollback',
                'private/signed URL handling for sensitive docs',
            ],
            'out_of_scope' => [
                'object storage migration without local backup and rollback plan',
                'exposing KTP/NIK/scanned docs publicly',
            ],
            'production_safety_rule' => 'No object storage migration without local backup and rollback plan; sensitive docs stay private.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['storage readiness + migration/rollback plan documented', 'sensitive-doc privacy preserved', 'foundation GO preserved'],
            'watch_criteria' => ['migration executed for subset of buckets'],
            'no_go_criteria' => ['no rollback plan', 'public exposure of sensitive docs', 'foundation GO regressed'],
            'deliverables' => ['object storage readiness doc', 'migration/rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'STATELESS-1',
            'title' => 'Stateless App Readiness',
            'status' => 'completed',
            'priority' => 9,
            'depends_on' => ['STORAGE-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'stateless_governance',
            'readiness_command' => 'runtime:stateless-readiness-check',
            'go_tag' => 'stateless-1-runtime-statelessness-deploy-portability-foundation-go',
            'go_commit' => 'c0cff0c',
            'objective' => 'Make the app stateless (session/cache/queue/storage externalized) so multiple instances can run behind a load balancer.',
            'why_this_order' => 'Depends on object storage; must be GO before the load balancer pilot.',
            'allowed_scope' => [
                'externalized session/cache/file storage readiness',
                'stateless readiness checklist + audit',
                'sticky-session removal design',
            ],
            'out_of_scope' => ['starting the load balancer pilot', 'local-disk session/asset dependencies'],
            'production_safety_rule' => 'Stateless readiness must be GO before LB-1; no local-only state on request path.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['stateless readiness audit passes', 'no local-only request state', 'foundation GO preserved'],
            'watch_criteria' => ['residual local state documented as backlog'],
            'no_go_criteria' => ['request-path local state remains', 'foundation GO regressed'],
            'deliverables' => ['stateless readiness audit', 'externalization design', 'evidence doc'],
        ],
        [
            'id' => 'LB-1',
            'title' => 'Load Balancer Pilot',
            'status' => 'completed',
            'priority' => 10,
            'depends_on' => ['STATELESS-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'lb_governance',
            'readiness_command' => 'lb:readiness-check',
            'go_tag' => 'lb-1-load-balancer-pilot-go',
            'go_commit' => '1be6f50',
            'objective' => 'Pilot a load balancer in front of stateless app instances, gated on STATELESS-1 GO.',
            'why_this_order' => 'Load balancer requires stateless readiness and precedes read-replica production routing.',
            'allowed_scope' => [
                'load balancer pilot design (health checks, draining)',
                'multi-instance pilot on non-production or gated path',
                'failover/rollback plan',
            ],
            'out_of_scope' => ['LB pilot before stateless readiness GO', 'routing read traffic to replica'],
            'production_safety_rule' => 'No load balancer pilot until stateless readiness is GO.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['LB pilot validated with health checks + rollback', 'STATELESS-1 GO confirmed', 'foundation GO preserved'],
            'watch_criteria' => ['pilot limited to staging/gated traffic'],
            'no_go_criteria' => ['stateless not GO', 'foundation GO regressed'],
            'deliverables' => ['LB pilot design', 'failover/rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'REPLICA-1',
            'title' => 'Read Replica Readiness',
            'status' => 'completed',
            'priority' => 11,
            'depends_on' => ['LB-1', 'CACHE-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'readiness_only' => true,
            'governance_section' => 'database_replica_governance',
            'readiness_command' => 'db:replica-readiness-check',
            'go_tag' => 'replica-1-read-replica-readiness-database-scale-foundation-go',
            'go_commit' => 'bca0f645e22da091b14cf03bb83b74c9c5449c98',
            'objective' => 'Prepare read-replica readiness (replication + read/write split design) WITHOUT routing production read traffic to the replica unless explicitly approved.',
            'why_this_order' => 'Read replica follows cache (offload) and load balancer (routing capability); readiness-only until approved.',
            'allowed_scope' => [
                'replication topology + lag monitoring design',
                'read/write connection split design',
                'read-consistency risk analysis',
            ],
            'out_of_scope' => [
                'routing production read traffic to replica without explicit approval',
                'stale-read-sensitive financial/inventory reads on replica',
            ],
            'production_safety_rule' => 'No read traffic redirected to replica unless explicitly approved.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['replica readiness + read/write split design documented', 'no production read routing enabled', 'foundation GO preserved'],
            'watch_criteria' => ['replica provisioned but routing kept off pending approval'],
            'no_go_criteria' => ['production reads routed to replica without approval', 'foundation GO regressed'],
            'deliverables' => ['replica readiness design', 'read/write split design', 'evidence doc'],
        ],
        [
            'id' => 'CACHE-1-REDIS-READINESS',
            'title' => 'Redis Shared Cache & Session Readiness',
            'status' => 'completed',
            'priority' => 12,
            'depends_on' => ['REPLICA-1'],
            'category' => 'cache',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'disambiguates' => 'CACHE-1',
            'disambiguation_note' => 'Distinct from CACHE-1 (Cache Strategy, Redis Readiness & Invalidation Governance, priority 3) which was the earlier design-only cache/invalidation governance sprint. This entry is the later Redis shared cache + session runtime-readiness sprint (cache_redis_governance).',
            'governance_section' => 'cache_redis_governance',
            'readiness_command' => 'cache:redis-readiness-check',
            'go_tag' => 'cache-1-redis-shared-cache-session-readiness-go',
            'go_commit' => 'be9c2d7',
            'objective' => 'Prepare Redis-backed shared cache and session readiness (config/env only) distinct from the earlier CACHE-1 invalidation-governance design sprint.',
            'why_this_order' => 'Runs after REPLICA-1 readiness in the actual delivery sequence; readiness/config-only, no forced runtime driver change.',
            'allowed_scope' => ['Redis cache/session readiness config', 'redis readiness check command', 'governance rules'],
            'out_of_scope' => ['forcing Redis as the production cache/session driver', 'critical financial/inventory caching without invalidation tests'],
            'production_safety_rule' => 'Redis readiness is opt-in via config; no runtime driver forced by this sprint.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['redis readiness command GO', 'cache_redis_governance rules published', 'foundation GO preserved'],
            'watch_criteria' => ['redis not yet the active driver on VPS pilot'],
            'no_go_criteria' => ['critical value cached without invalidation test', 'foundation GO regressed'],
            'deliverables' => ['cache_redis_governance rules', 'redis readiness command', 'evidence doc'],
        ],
        [
            'id' => 'OBS-1',
            'title' => 'Request ID, Correlation ID & Observability Foundation',
            'status' => 'completed',
            'priority' => 13,
            'depends_on' => ['CACHE-1-REDIS-READINESS'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'governance_section' => 'observability_governance',
            'readiness_command' => 'obs:readiness-check',
            'go_tag' => 'obs-1-request-id-correlation-observability-foundation-go',
            'go_commit' => 'df07d90',
            'objective' => 'Attach a bounded request/correlation id and PII-free log context to every request for cross-cutting traceability.',
            'why_this_order' => 'Observability/request-id foundation follows cache/replica readiness so future scale-out work is traceable.',
            'allowed_scope' => ['request/correlation id middleware', 'PII-free log context', 'readiness command'],
            'out_of_scope' => ['external monitoring vendor', 'log/session/cache/queue driver change'],
            'production_safety_rule' => 'No PII/secret in request/correlation id context; inbound ids only trusted when explicitly configured.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['observability readiness command GO', 'request id header present', 'foundation GO preserved'],
            'watch_criteria' => ['multi-node id propagation deferred to LB/REPLICA scale-out'],
            'no_go_criteria' => ['PII/secret exposed in log context', 'foundation GO regressed'],
            'deliverables' => ['observability_governance rules', 'request correlation middleware', 'evidence doc'],
        ],
        [
            'id' => 'OBS-2',
            'title' => 'Centralized Logging & Error Tracking Readiness',
            'status' => 'completed',
            'priority' => 14,
            'depends_on' => ['OBS-1'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'observability_pipeline_governance',
            'readiness_command' => 'obs:pipeline-readiness-check',
            'go_tag' => 'obs-2-centralized-logging-error-tracking-readiness-go',
            'go_commit' => '5cb632c',
            'objective' => 'Prepare readiness (config/rules only) for a future centralized log collector and error tracker, OFF by default.',
            'why_this_order' => 'Centralized logging/error-tracking readiness follows the OBS-1 request/correlation id foundation it depends on for event correlation.',
            'allowed_scope' => ['central logging/error tracking readiness config', 'readiness command', 'governance rules'],
            'out_of_scope' => ['installing an external monitoring vendor', 'sending PII/log traffic externally'],
            'production_safety_rule' => 'Central logging/error tracking stay OFF by default; no PII/secret ever exported.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['pipeline readiness command GO', 'PII-send risk check enforced', 'foundation GO preserved'],
            'watch_criteria' => ['no external vendor connected yet — readiness only'],
            'no_go_criteria' => ['PII/secret sent externally', 'foundation GO regressed'],
            'deliverables' => ['observability_pipeline_governance rules', 'pipeline readiness command', 'evidence doc'],
        ],
        [
            'id' => 'ROADMAP-1-CANONICALIZATION',
            'title' => 'Foundation Roadmap Canonicalization',
            'status' => 'completed',
            'priority' => 15,
            'depends_on' => ['OBS-2'],
            'category' => 'governance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'disambiguates' => 'ROADMAP-1',
            'disambiguation_note' => 'Distinct from the top-level roadmap_id ROADMAP-1 (this file\'s own original source-lock identity, tag roadmap-1-national-foundation-expansion-source-lock-go). This entry is the later canonicalization sprint that re-synced completed/next status after STORAGE-1..OBS-2.',
            'governance_section' => 'roadmap_governance',
            'readiness_command' => 'foundation:roadmap-check',
            'go_tag' => 'roadmap-1-foundation-roadmap-canonicalization-go',
            'objective' => 'Canonicalize this roadmap so completed/next status matches actual delivered foundation sprints (STORAGE-1..OBS-2), never pointing next_recommended_sprint back at a completed sprint.',
            'why_this_order' => 'Canonicalization must run after the sprints it reconciles (OBS-2) so it can correct their recorded status in one pass.',
            'allowed_scope' => ['roadmap config staleness fixes', 'roadmap governance rules', 'roadmap check command', 'docs'],
            'out_of_scope' => ['runtime driver change', 'business workflow change', 'new external dependency'],
            'production_safety_rule' => 'Governance/config/docs only; no runtime driver, migration, or workflow change.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['roadmap check command GO', 'next_recommended_sprint not stale', 'foundation GO preserved'],
            'watch_criteria' => ['legacy pre-STORAGE-1 sprints not retrofitted with go_tag metadata'],
            'no_go_criteria' => ['next_recommended_sprint points at a completed sprint', 'foundation GO regressed'],
            'deliverables' => ['foundation_roadmap.php canonicalization', 'roadmap_governance rules', 'foundation:roadmap-check command', 'evidence doc'],
        ],
        [
            'id' => 'ENT-0',
            'title' => 'Enterprise Foundation Freeze Rules & Roadmap Reconciliation',
            'status' => 'completed',
            'priority' => 16,
            'depends_on' => ['ROADMAP-1-CANONICALIZATION'],
            'category' => 'governance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'go_tag' => 'ent-0-enterprise-foundation-freeze-rules-roadmap-reconciliation-go',
            'go_commit' => '8b0fa2d3670a8ce6632a9bd76ad7e4d49b512868',
            'related_shipped_foundations' => [
                'NSF-9', 'NSF-10', 'CACHE-1', 'QUEUE-1', 'DBPERF-1', 'DBPERF-2', 'RPT-1',
                'STORAGE-1', 'STATELESS-1', 'LB-1', 'REPLICA-1', 'CACHE-1-REDIS-READINESS',
                'OBS-1', 'OBS-2', 'ROADMAP-1-CANONICALIZATION',
            ],
            'objective' => 'Register the Enterprise Foundation Freeze Rules as durable governance and reconcile the locked ENT-1..ENT-16 enterprise foundation sequence into this canonical roadmap without re-marking partially overlapping shipped work as complete.',
            'why_this_order' => 'The freeze rules and ENT sequence must be canonical (ROADMAP-R001/R002) before ENT-1 starts, and must run after ROADMAP-1-CANONICALIZATION so the reconciled baseline is already de-staled.',
            'allowed_scope' => [
                'freeze rules governance doc (docs/architecture/enterprise-foundation-freeze-rules.md)',
                'ENT-1..ENT-16 registration + overlap mapping in this config',
                'roadmap/governance test updates',
            ],
            'out_of_scope' => [
                'any runtime driver, migration, schema, route, permission, or business workflow change',
                'marking any ENT-1..ENT-16 sprint completed without its own evidence and GO tag',
            ],
            'production_safety_rule' => 'Governance/config/docs/tests only; no deploy, no runtime change; freeze rules doc must never contain release-evidence forbidden literals.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'freeze rules doc committed and referenced as canonical governance',
                'ENT-1..ENT-16 registered planned with resolvable dependencies',
                'next_recommended_sprint resolves to ENT-1 and is not stale',
                'foundation GO preserved',
            ],
            'watch_criteria' => ['MON-1 consolidation into ENT-8 deferred to a later governance sprint'],
            'no_go_criteria' => ['shipped foundation falsely re-marked as an ENT completion', 'foundation GO regressed'],
            'deliverables' => ['enterprise-foundation-freeze-rules.md', 'ENT roadmap reconciliation', 'evidence in sprint summary'],
        ],
        [
            'id' => 'ENT-1',
            'title' => 'Enterprise Architecture Baseline Lock',
            'status' => 'completed',
            'priority' => 17,
            'depends_on' => ['ENT-0'],
            'category' => 'architecture',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'baseline_doc' => 'docs/architecture/enterprise-architecture-baseline-lock.md',
            'go_tag' => 'ent-1-enterprise-architecture-baseline-lock-go',
            'go_commit' => '9069bce8d9f63c7a575a251c997cc2c8d44a83bd',
            'deploy_evidence_commit' => '62c4ff0',
            'related_shipped_foundations' => ['STORAGE-1', 'STATELESS-1', 'LB-1', 'ROADMAP-1-CANONICALIZATION'],
            'objective' => 'Lock the enterprise architecture baseline (Controller → FormRequest → Service → RepositoryInterface → Repository → Model, policy-gated, branch-isolated) as an auditable governance check on top of the shipped foundation governance summary.',
            'why_this_order' => 'Every later ENT sprint builds on an explicit, checkable architecture baseline.',
            'allowed_scope' => ['architecture baseline governance check/command', 'baseline documentation', 'no-new-pattern guardrails'],
            'out_of_scope' => ['architecture pattern changes', 'React/Vue introduction', 'large refactors'],
            'production_safety_rule' => 'Baseline lock is read-only governance; no runtime behavior change.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['architecture baseline check available and GO', 'foundation GO preserved'],
            'watch_criteria' => ['baseline documented but automated check partial'],
            'no_go_criteria' => ['architecture contract weakened', 'foundation GO regressed'],
            'deliverables' => ['architecture baseline governance check', 'evidence doc'],
        ],
        [
            'id' => 'ENT-2',
            'title' => 'Database Performance Contract',
            'status' => 'completed',
            'priority' => 18,
            'depends_on' => ['ENT-1', 'DBPERF-1', 'DBPERF-2'],
            'category' => 'db_performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'contract_doc' => 'docs/architecture/database-performance-contract.md',
            'hotspot_inventory_doc' => 'docs/architecture/database-performance-hotspot-inventory.md',
            'go_tag' => 'ent-2-database-performance-contract-go',
            'go_commit' => '89e641d31b43820873d44db196a53da56cc3175b',
            'deploy_evidence_commit' => '22a411d',
            'related_shipped_foundations' => ['DBPERF-1', 'DBPERF-2'],
            'objective' => 'Turn the shipped DBPERF-1 index/EXPLAIN audit and DBPERF-2 pooling/tuning design into an enforceable database performance contract (heavy-query audit, additive-only migrations, named indexes).',
            'why_this_order' => 'Performance contract must be locked before reporting expansion and load tests measure against it.',
            'allowed_scope' => ['heavy-query audit contract', 'EXPLAIN evidence requirements', 'additive index governance'],
            'out_of_scope' => ['destructive schema rewrites', 'migrate:fresh/db:wipe on VPS'],
            'production_safety_rule' => 'Additive migrations only; nullable/default-safe columns on production tables.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['performance contract documented + checkable', 'foundation GO preserved'],
            'watch_criteria' => ['contract enforced on hot paths first, remainder backlogged'],
            'no_go_criteria' => ['destructive migration', 'foundation GO regressed'],
            'deliverables' => ['db performance contract', 'evidence doc'],
        ],
        [
            'id' => 'ENT-3',
            'title' => 'Reporting Materialized Summary Expansion',
            'status' => 'completed',
            'priority' => 19,
            'depends_on' => ['ENT-2', 'RPT-1'],
            'category' => 'reporting',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'contract_doc' => 'docs/architecture/reporting-materialized-summary-contract.md',
            'candidate_inventory_doc' => 'docs/architecture/reporting-summary-candidate-inventory.md',
            'go_tag' => 'ent-3-reporting-materialized-summary-expansion-go',
            'go_commit' => '359f884a566c601a48f6ab6461c71a5efa9839ed',
            'deploy_evidence_commit' => '3c98165',
            'related_shipped_foundations' => ['RPT-1'],
            'objective' => 'Expand the shipped RPT-1 rpt_*/materialized-summary foundation so heavy dashboards/reports read from summaries instead of raw transactions.',
            'why_this_order' => 'Reporting expansion needs the ENT-2 performance contract and precedes load-test baselining of report pages.',
            'allowed_scope' => ['rpt_* expansion', 'materialized summary rollout', 'stale/refresh policy'],
            'out_of_scope' => ['KTP/NIK or raw clinical notes in summaries', 'destructive replacement of transactional tables'],
            'production_safety_rule' => 'Additive rpt_* only; refresh must not lock hot tables; PII never summarized unmasked.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['heavy reports routed to summaries with tests', 'foundation GO preserved'],
            'watch_criteria' => ['subset of reports migrated, remainder backlogged'],
            'no_go_criteria' => ['PII in summaries', 'foundation GO regressed'],
            'deliverables' => ['expanded rpt_* summaries', 'evidence doc'],
        ],
        [
            'id' => 'ENT-4',
            'title' => 'Redis Cache Enterprise Policy',
            'status' => 'completed',
            'priority' => 20,
            'depends_on' => ['ENT-1', 'CACHE-1', 'CACHE-1-REDIS-READINESS'],
            'category' => 'cache',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'policy_doc' => 'docs/architecture/redis-cache-enterprise-policy.md',
            'ttl_matrix_doc' => 'docs/architecture/cache-ttl-matrix.md',
            'invalidation_matrix_doc' => 'docs/architecture/cache-invalidation-matrix.md',
            'readiness_runbook_doc' => 'docs/architecture/redis-readiness-runbook.md',
            'go_tag' => 'ent-4-redis-cache-enterprise-policy-go',
            'go_commit' => '9c15db2d9777d0d91243c8737fb5f4963200634d',
            'deploy_evidence_commit' => '321c05d',
            'related_shipped_foundations' => ['CACHE-1', 'CACHE-1-REDIS-READINESS'],
            'disambiguation_note' => 'Builds on BOTH shipped cache sprints — CACHE-1 (invalidation governance design, cache_governance) and CACHE-1-REDIS-READINESS (Redis runtime readiness, cache_redis_governance) — into one enforced enterprise cache policy. Not a duplicate of either.',
            'objective' => 'Enforce the enterprise Redis cache policy: standard key prefixes (domain/branch/filter/version), explicit TTL, clear invalidation, no raw PII cached, cache as accelerator never source of truth.',
            'why_this_order' => 'Cache policy enforcement follows the architecture baseline and precedes queue/load-test sprints that depend on cache behavior.',
            'allowed_scope' => ['cache key/TTL/invalidation policy enforcement', 'cache governance command expansion'],
            'out_of_scope' => ['caching critical mutable financial/inventory values without invalidation tests', 'raw PII in cache'],
            'production_safety_rule' => 'No PII cached raw; no critical value cached without invalidation tests.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['enterprise cache policy enforced + tested', 'foundation GO preserved'],
            'watch_criteria' => ['policy enforced on new caches first, legacy caches backlogged'],
            'no_go_criteria' => ['cache used as source of truth for transactions', 'foundation GO regressed'],
            'deliverables' => ['enterprise cache policy', 'TTL matrix', 'invalidation matrix', 'Redis readiness runbook', 'evidence doc'],
        ],
        [
            'id' => 'ENT-5',
            'title' => 'Queue, Retry & Failed Job Governance',
            'status' => 'completed',
            'priority' => 21,
            'depends_on' => ['ENT-1', 'QUEUE-1'],
            'category' => 'queue',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'queue_retry_governance',
            'readiness_command' => 'foundation:queue-retry-failed-job-check',
            'policy_doc' => 'docs/architecture/queue-retry-failed-job-governance.md',
            'worker_runbook_doc' => 'docs/architecture/queue-worker-operations-runbook.md',
            'go_tag' => 'ent-5-queue-retry-failed-job-governance-go',
            'go_commit' => 'b83d62ed02eec098da7f229afda898527a328f44',
            'related_shipped_foundations' => ['QUEUE-1'],
            'disambiguation_note' => 'Operationalizes the shipped QUEUE-1 foundation (queue_governance section, foundation:queue-governance-check) with an enforced retry/backoff/timeout standard, failed-job storage governance, and a ShouldQueue convention scan (queue_retry_governance section). Not a duplicate of QUEUE-1.',
            'objective' => 'Operationalize the shipped QUEUE-1 design: heavy work moved to queue, retry policies mandatory, failed jobs visible and actionable, queue health in observability.',
            'why_this_order' => 'Queue governance precedes idempotency/outbox implementation and async report/export work.',
            'allowed_scope' => ['queue-readiness for heavy flows', 'retry/failed-job governance', 'queue health checks'],
            'out_of_scope' => ['auto-send WhatsApp', 'payment rollback caused by secondary job failure'],
            'production_safety_rule' => 'No queue job without retry/failure policy; payments never roll back for secondary job failures.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['queue/retry/failed-job governance enforced', 'foundation GO preserved'],
            'watch_criteria' => ['subset of heavy flows queued, remainder backlogged'],
            'no_go_criteria' => ['job without retry policy shipped', 'foundation GO regressed'],
            'deliverables' => ['queue governance enforcement', 'evidence doc'],
        ],
        [
            'id' => 'ENT-6',
            'title' => 'Idempotency & Outbox Foundation',
            'status' => 'completed',
            'priority' => 22,
            'depends_on' => ['ENT-5', 'QUEUE-1'],
            'category' => 'queue',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'idempotency_outbox_governance',
            'readiness_command' => 'foundation:idempotency-outbox-check',
            'policy_doc' => 'docs/architecture/idempotency-outbox-foundation-governance.md',
            'go_tag' => 'ent-6-idempotency-outbox-foundation-go',
            'go_commit' => '46f41e8893a1892b9c725daefbf43d41ced967cd',
            'related_shipped_foundations' => ['QUEUE-1'],
            'disambiguation_note' => 'Hardens and enterprise-locks the shipped QUEUE-1 idempotency/outbox primitives. This keeps QUEUE-1 commands/services intact and adds ENT-6 governance without enabling external dispatch.',
            'objective' => 'Implement the QUEUE-1 idempotency-key convention and outbox pattern for important cross-module events ahead of any external (WA/API) integration.',
            'why_this_order' => 'Idempotency/outbox must exist before external integrations; depends on ENT-5 queue governance.',
            'allowed_scope' => ['idempotency key enforcement', 'outbox dispatch for cross-module events'],
            'out_of_scope' => ['direct external sends from request path', 'auto-creating LabOrder from RME payment'],
            'production_safety_rule' => 'RME payment → LabCaseCandidate stays idempotent; external integrations only via queue/outbox.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['idempotency + outbox enforced with tests', 'foundation GO preserved'],
            'watch_criteria' => ['outbox adopted for a subset of events, remainder backlogged'],
            'no_go_criteria' => ['non-idempotent job on critical flow', 'foundation GO regressed'],
            'deliverables' => ['idempotency/outbox implementation', 'evidence doc'],
        ],
        [
            'id' => 'ENT-7',
            'title' => 'Developer Assistance Console',
            'status' => 'completed',
            'priority' => 23,
            'depends_on' => ['ENT-1', 'OBS-1', 'OBS-2'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'developer_console_governance',
            'readiness_command' => 'foundation:developer-console-check',
            'policy_doc' => 'docs/architecture/developer-assistance-console-governance.md',
            'go_tag' => 'ent-7-developer-assistance-console-go',
            'go_commit' => 'a02da9f5a37d69feeae6d03ebbc77ebec9239237',
            'deploy_evidence_commit' => '0250ef4',
            'related_shipped_foundations' => ['OBS-1', 'OBS-2'],
            'disambiguation_note' => 'Read-only Super-Admin console consuming OBS-1/OBS-2, ENT-5, and ENT-6 surfaces. It adds no runtime driver change and does not replace the ENT-8 health pack.',
            'objective' => 'Provide a Super-Admin-only Developer Assistance console reading app/error logs, failed jobs, audit events, slow-query summary, deploy evidence, storage permission status, DB/Redis/queue health, and disk/backup status — all PII-masked.',
            'why_this_order' => 'Console consumes the OBS-1/OBS-2 correlation + pipeline readiness foundations and feeds ENT-8 health packs.',
            'allowed_scope' => ['read-only console surfaces', 'permission-gated + audited access', 'PII/secret masking'],
            'out_of_scope' => ['showing passwords/tokens/sessions/cookies/API keys/environment file contents', 'full KTP/NIK display'],
            'production_safety_rule' => 'Console is read-only, Super-Admin/permission-gated, audited, PII-masked.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['console live with masking + audit trail', 'foundation GO preserved'],
            'watch_criteria' => ['subset of surfaces live, remainder backlogged'],
            'no_go_criteria' => ['secret or full PII rendered', 'foundation GO regressed'],
            'deliverables' => ['developer assistance console', 'evidence doc'],
        ],
        [
            'id' => 'ENT-8',
            'title' => 'Observability & Health Check Pack',
            'status' => 'completed',
            'priority' => 24,
            'depends_on' => ['ENT-7', 'OBS-2', 'LB-1'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'health_check_governance',
            'readiness_command' => 'foundation:health-check',
            'policy_doc' => 'docs/architecture/observability-health-check-pack-governance.md',
            'go_tag' => 'ent-8-observability-health-check-pack-go',
            'go_commit' => '8f259bcd0bc0511b016492cd977cbe1aa347838a',
            'deploy_evidence_commit' => '982ac44',
            'related_shipped_foundations' => ['OBS-1', 'OBS-2', 'LB-1'],
            'disambiguation_note' => 'Overlaps the older planned MON-1 (Health Monitoring, Alerting & Uptime Readiness, now queued after the ENT sequence). MON-1 may be consolidated into ENT-8 via a later governance sprint; until then both stay registered and distinct.',
            'objective' => 'Ship the enterprise health-check pack: DB/Redis/queue/storage health, uptime/alerting readiness, building on OBS-1/OBS-2 and the LB-1 /health/lb endpoint.',
            'why_this_order' => 'Health pack needs the console (ENT-7) and shipped observability readiness; precedes security/load-test phases that consume its signals.',
            'allowed_scope' => ['health check endpoints/commands', 'alerting threshold readiness', 'queue/db/redis/storage health'],
            'out_of_scope' => ['external paging vendor without privacy review', 'PII/secret in health output'],
            'production_safety_rule' => 'Health endpoints stay minimal and non-sensitive; no PII/secret in alerts.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['health pack live + smoke-verified', 'foundation GO preserved'],
            'watch_criteria' => ['alerting readiness present but external channel deferred'],
            'no_go_criteria' => ['sensitive data in health/alert output', 'foundation GO regressed'],
            'deliverables' => ['health check pack', 'evidence doc'],
        ],
        [
            'id' => 'ENT-9',
            'title' => 'Security & PII Compliance Hardening',
            'status' => 'completed',
            'priority' => 25,
            'depends_on' => ['ENT-1'],
            'category' => 'security',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'security_compliance_governance',
            'readiness_command' => 'foundation:security-compliance-check',
            'policy_doc' => 'docs/architecture/security-pii-compliance-hardening-governance.md',
            'go_tag' => 'ent-9-security-pii-compliance-hardening-go',
            'go_commit' => '467b0ffc1f4a17740d17dc788c6db5e3fd67b3ab',
            'deploy_evidence_commit' => '8915c17',
            'related_shipped_foundations' => ['NSF-10'],
            'objective' => 'Harden KTP/NIK masking, audit coverage, export gating, and branch isolation across all modules to the enterprise standard.',
            'why_this_order' => 'Security/PII hardening must be locked before CI/CD gates encode it and before load tests run on realistic data.',
            'allowed_scope' => ['PII masking coverage', 'audit event coverage', 'branch isolation test hardening', 'export permission gates'],
            'out_of_scope' => ['cross-branch patient search by name/KTP', 'weakening any existing gate'],
            'production_safety_rule' => 'Full KTP/NIK server-side only; sidebar is never a security boundary.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['masking/audit/isolation hardening evidenced', 'foundation GO preserved'],
            'watch_criteria' => ['module-by-module rollout with backlog'],
            'no_go_criteria' => ['unmasked PII surface found and unfixed', 'foundation GO regressed'],
            'deliverables' => ['security/PII hardening pack', 'evidence doc'],
        ],
        [
            'id' => 'ENT-10',
            'title' => 'CI/CD Enterprise Gate',
            'status' => 'completed',
            'priority' => 26,
            'depends_on' => ['ENT-1', 'NSF-9', 'NSF-10'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'cicd_enterprise_gate_governance',
            'readiness_command' => 'foundation:cicd-enterprise-gate-check',
            'policy_doc' => 'docs/architecture/cicd-enterprise-gate-governance.md',
            'go_tag' => 'ent-10-cicd-enterprise-gate-go',
            'go_commit' => 'cbf4d12f790fe1788dbb0928fb9f96f050139b06',
            'deploy_evidence_commit' => '858f457',
            'related_shipped_foundations' => ['NSF-9', 'NSF-10'],
            'objective' => 'Extend the shipped NSF-9/NSF-10 flag/smoke/evidence gates into a full CI/CD enterprise gate: critical tests, migration safety, route/config sanity, smoke commands.',
            'why_this_order' => 'CI/CD gate must encode the earlier ENT contracts before deploy/rollback automation relies on it.',
            'allowed_scope' => ['CI gate expansion', 'migration-safety check', 'route/config sanity checks'],
            'out_of_scope' => ['ignoring failed CI', 'merging without relevant tests'],
            'production_safety_rule' => 'Failed CI blocks merge; no gate may be skipped silently.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['enterprise CI gate running on PRs', 'foundation GO preserved'],
            'watch_criteria' => ['gate advisory-only for a bounded burn-in window'],
            'no_go_criteria' => ['gate bypassed on failure', 'foundation GO regressed'],
            'deliverables' => ['CI/CD enterprise gate', 'evidence doc'],
        ],
        [
            'id' => 'ENT-11',
            'title' => 'Deployment & Rollback Automation',
            'status' => 'completed',
            'priority' => 27,
            'depends_on' => ['ENT-10'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'deployment_rollback_governance',
            'readiness_command' => 'foundation:deployment-rollback-check',
            'policy_doc' => 'docs/architecture/deployment-rollback-automation-governance.md',
            'go_tag' => 'ent-11-deployment-rollback-automation-go',
            'go_commit' => '85ca36b7ea257a8fe5dba1031672b367954605d0',
            'deploy_evidence_commit' => 'aa14d9d',
            'related_shipped_foundations' => ['NSF-10', 'LB-1'],
            'objective' => 'Automate the VPS deploy path (backup → deploy → cache rebuild → permission reset → smoke) and a tested rollback path, building on the existing deploy script.',
            'why_this_order' => 'Deploy/rollback automation requires the CI gate and precedes backup/DR automation drills.',
            'allowed_scope' => ['deploy automation hardening', 'rollback automation + rehearsal', 'deploy evidence capture'],
            'out_of_scope' => ['migrate:fresh/db:wipe on VPS', 'deploy without DB backup'],
            'production_safety_rule' => 'Backup failure stops deploy; every deploy has a rollback plan.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['automated deploy + rehearsed rollback evidenced', 'foundation GO preserved'],
            'watch_criteria' => ['rollback rehearsed on staging only'],
            'no_go_criteria' => ['deploy without backup', 'foundation GO regressed'],
            'deliverables' => ['deploy/rollback automation', 'evidence doc'],
        ],
        [
            'id' => 'ENT-12',
            'title' => 'Backup & Disaster Recovery Automation',
            'status' => 'completed',
            'priority' => 28,
            'depends_on' => ['ENT-11', 'NSF-10'],
            'category' => 'backup_dr',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'backup_dr_governance',
            'readiness_command' => 'foundation:backup-dr-check',
            'policy_doc' => 'docs/architecture/backup-disaster-recovery-automation-governance.md',
            'go_tag' => 'ent-12-backup-disaster-recovery-automation-go',
            'go_commit' => 'b6a0e6536f764de9eef0b48e8e8d3498ff939516',
            'deploy_evidence_commit' => 'c8fad61',
            'related_shipped_foundations' => ['NSF-10'],
            'objective' => 'Automate DB + storage backup with retention, periodic restore rehearsal with evidence, and RTO/RPO targets.',
            'why_this_order' => 'DR readiness is a hard prerequisite of Enterprise Foundation Closure GO and must precede load-test phases that certify scale.',
            'allowed_scope' => ['backup automation + retention', 'restore rehearsal to non-production', 'RTO/RPO definition'],
            'out_of_scope' => ['restore drills that endanger the VPS pilot'],
            'production_safety_rule' => 'Restore rehearsal never targets the production database; evidence records path + size.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['automated backup + restore rehearsal evidence', 'RTO/RPO documented', 'foundation GO preserved'],
            'watch_criteria' => ['storage-file backup strategy phased after DB backup'],
            'no_go_criteria' => ['no verified restore path', 'foundation GO regressed'],
            'deliverables' => ['backup/DR automation', 'restore rehearsal evidence', 'evidence doc'],
        ],
        [
            'id' => 'ENT-13',
            'title' => 'Load Test 5 Cabang Baseline',
            'status' => 'completed',
            'priority' => 29,
            'depends_on' => ['ENT-2', 'ENT-4', 'ENT-12'],
            'category' => 'performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'load_test_baseline_governance',
            'readiness_command' => 'foundation:load-test-baseline-check',
            'policy_doc' => 'docs/architecture/load-test-5-cabang-baseline-governance.md',
            'go_tag' => 'ent-13-load-test-5-cabang-baseline-go',
            'go_commit' => 'dda9b873bc47c53b9fccba7934a5999cc7e28cde',
            'deploy_evidence_commit' => 'c7f39f0',
            'related_shipped_foundations' => ['DBPERF-1', 'DBPERF-2', 'RPT-1'],
            'objective' => 'Run the 5-branch baseline load test (25 clinic + 2 lab + 2 inventory users, 60k–70k patients) across RME, cashier, owner dashboard, inventory, reports, and RM lookup pages.',
            'why_this_order' => 'Baseline load test validates the ENT performance/cache/DR foundations before scale projection.',
            'allowed_scope' => ['load test harness + dataset', 'bottleneck categorization (DB/cache/queue/PHP/network/frontend/storage)', 'slow-query follow-up list'],
            'out_of_scope' => ['load testing against the production VPS pilot database'],
            'production_safety_rule' => 'Load tests run on non-production data/environments only.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['baseline results in evidence pack with 200–300ms targets assessed', 'foundation GO preserved'],
            'watch_criteria' => ['heavy report pages moved to async/export instead of real-time'],
            'no_go_criteria' => ['scalability claimed without evidence', 'foundation GO regressed'],
            'deliverables' => ['5-branch load test evidence pack', 'evidence doc'],
        ],
        [
            'id' => 'ENT-14',
            'title' => 'Load Test Scale Projection',
            'status' => 'completed',
            'priority' => 30,
            'depends_on' => ['ENT-13'],
            'category' => 'performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'load_test_scale_projection_governance',
            'readiness_command' => 'foundation:load-test-scale-projection-check',
            'policy_doc' => 'docs/architecture/load-test-scale-projection-governance.md',
            'go_tag' => 'ent-14-load-test-scale-projection-go',
            'go_commit' => '7fe8a36f2afcaba53dd3c6134b792af0a34fbea8',
            'deploy_evidence_commit' => '86ef921',
            'related_shipped_foundations' => ['REPLICA-1', 'LB-1'],
            'objective' => 'Project 20-branch and national scale from the ENT-13 baseline, tying results to the shipped LB/replica readiness foundations.',
            'why_this_order' => 'Scale projection needs the measured baseline and precedes documentation/closure.',
            'allowed_scope' => ['20-branch + national projection', 'capacity model per bottleneck category'],
            'out_of_scope' => ['activating replica read routing or multi-node traffic as part of the projection'],
            'production_safety_rule' => 'Projection is analysis-only; no production topology change.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['scale projection documented in evidence pack', 'foundation GO preserved'],
            'watch_criteria' => ['projection pending one deferred bottleneck fix'],
            'no_go_criteria' => ['projection without baseline evidence', 'foundation GO regressed'],
            'deliverables' => ['scale projection report', 'evidence doc'],
        ],
        [
            'id' => 'ENT-15',
            'title' => 'Enterprise Documentation & Runbook',
            'status' => 'completed',
            'priority' => 31,
            'depends_on' => ['ENT-14'],
            'category' => 'documentation',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'governance_section' => 'enterprise_documentation_governance',
            'readiness_command' => 'foundation:enterprise-documentation-check',
            'policy_doc' => 'docs/architecture/enterprise-documentation-runbook-governance.md',
            'go_tag' => 'ent-15-enterprise-documentation-runbook-go',
            'go_commit' => '41fedc79c03780b24d5e39f5aa50f706bb4d7a73',
            'related_shipped_foundations' => ['ROADMAP-1-CANONICALIZATION'],
            'objective' => 'Consolidate enterprise documentation: runbooks, SOP incident, SOP deploy, architecture docs, and operator guides.',
            'why_this_order' => 'Documentation consolidates all prior ENT outputs right before closure GO/NO-GO.',
            'allowed_scope' => ['runbooks + SOPs', 'architecture doc consolidation', 'operator guides'],
            'out_of_scope' => ['secrets or full PII in documentation'],
            'production_safety_rule' => 'Docs never contain secrets, credentials, or unmasked PII.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['runbooks + SOPs complete and reviewed', 'foundation GO preserved'],
            'watch_criteria' => ['non-critical guides backlogged'],
            'no_go_criteria' => ['missing incident/deploy SOP', 'foundation GO regressed'],
            'deliverables' => ['enterprise runbook set', 'evidence doc'],
        ],
        [
            'id' => 'ENT-16',
            'title' => 'Enterprise Foundation Closure GO/NO-GO',
            'status' => 'planned',
            'priority' => 32,
            'depends_on' => [
                'ENT-1', 'ENT-2', 'ENT-3', 'ENT-4', 'ENT-5', 'ENT-6', 'ENT-7', 'ENT-8',
                'ENT-9', 'ENT-10', 'ENT-11', 'ENT-12', 'ENT-13', 'ENT-14', 'ENT-15',
            ],
            'category' => 'governance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Run the Enterprise Foundation Closure GO/NO-GO against the 13 closure criteria and, on GO, create the final enterprise-foundation-go tag ending the initial freeze.',
            'why_this_order' => 'Closure must be last in the ENT sequence; the national RC-1 consolidation remains the final roadmap item after it.',
            'allowed_scope' => ['closure evidence pack', 'GO/NO-GO decision record', 'final enterprise-foundation-go tag on GO'],
            'out_of_scope' => ['declaring GO with any ENT sprint incomplete', 'new feature scope'],
            'production_safety_rule' => 'GO only with full evidence pack; freeze rules stay in force until the tag exists.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined', 'roadmap'],
            'go_criteria' => ['all 13 closure criteria met with evidence', 'enterprise-foundation-go tag created', 'foundation GO preserved'],
            'watch_criteria' => ['closure deferred with named blocking ENT sprint'],
            'no_go_criteria' => ['closure criteria unmet', 'foundation GO regressed'],
            'deliverables' => ['closure evidence pack', 'enterprise-foundation-go tag'],
        ],
        [
            'id' => 'MON-1',
            'title' => 'Health Monitoring, Alerting & Uptime Readiness',
            'status' => 'planned',
            'priority' => 33,
            'depends_on' => ['ROADMAP-1-CANONICALIZATION'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Prepare health-monitoring, alerting, and uptime readiness (design/config first) building on OBS-1/OBS-2 and the LB-1 health endpoint.',
            'why_this_order' => 'Queued after the ENT-0 enterprise foundation sequence because its scope overlaps ENT-8 (Observability & Health Check Pack); it may be consolidated into ENT-8 by a later governance sprint.',
            'allowed_scope' => ['uptime/health-check readiness design', 'alerting threshold design (no external paging vendor required)', 'readiness command'],
            'out_of_scope' => ['external paging/on-call vendor integration without review', 'PII/secret in alerts'],
            'production_safety_rule' => 'No external alerting vendor without a privacy/rollback review; no PII/secret in alert payloads.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['monitoring/alerting readiness documented', 'foundation GO preserved'],
            'watch_criteria' => ['external alerting vendor deferred pending review'],
            'no_go_criteria' => ['PII/secret in alert payload', 'foundation GO regressed'],
            'deliverables' => ['monitoring readiness design', 'evidence doc'],
        ],
        [
            'id' => 'PART-1',
            'title' => 'Partitioning Design, Not Production Yet',
            'status' => 'planned',
            'priority' => 34,
            'depends_on' => ['DBPERF-1', 'RPT-1'],
            'category' => 'db_scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'production_forbidden' => true,
            'objective' => 'Design table partitioning strategy (range/list keys, migration path) as DESIGN ONLY — no production partition migration.',
            'why_this_order' => 'Partitioning design follows index audit and rpt_* summary; production migration is explicitly deferred.',
            'allowed_scope' => [
                'partition key + strategy design',
                'zero-downtime partition migration plan (design only)',
                'candidate table analysis',
            ],
            'out_of_scope' => [
                'any production partitioning migration',
                'destructive table rewrite',
            ],
            'production_safety_rule' => 'No direct production partitioning in PART-1; design/plan only.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['partition strategy + migration plan documented', 'no production partition migration performed', 'foundation GO preserved'],
            'watch_criteria' => ['candidate tables identified, plan pending review'],
            'no_go_criteria' => ['production partition migration attempted', 'foundation GO regressed'],
            'deliverables' => ['partitioning design', 'zero-downtime migration plan', 'evidence doc'],
        ],
        [
            'id' => 'SEARCH-1',
            'title' => 'Search Engine & Log Explorer Foundation',
            'status' => 'planned',
            'priority' => 35,
            'depends_on' => ['NSF-10', 'QUEUE-1'],
            'category' => 'search',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Introduce a search engine and log explorer foundation (indexing pipeline design) without exposing PII or secrets.',
            'why_this_order' => 'Search/log explorer follows observability hardening and queue (for async indexing).',
            'allowed_scope' => [
                'search index schema + async indexing design (via QUEUE-1)',
                'log explorer readiness with PII/secret redaction',
                'access control for search/log surfaces',
            ],
            'out_of_scope' => [
                'search/log explorer exposing PII/secrets',
                'indexing KTP/NIK/raw medical notes',
            ],
            'production_safety_rule' => 'No search/log explorer exposing PII/secrets.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['search/log design with redaction documented', 'access control defined', 'foundation GO preserved'],
            'watch_criteria' => ['indexing scope limited to non-sensitive fields initially'],
            'no_go_criteria' => ['PII/secrets indexed or exposed', 'foundation GO regressed'],
            'deliverables' => ['search foundation design', 'log explorer readiness', 'evidence doc'],
        ],
        [
            'id' => 'NDA-1',
            'title' => 'National Distributed Architecture Plan',
            'status' => 'planned',
            'priority' => 36,
            'depends_on' => ['REPLICA-1', 'LB-1', 'PART-1', 'STORAGE-1', 'SEARCH-1'],
            'category' => 'architecture',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Consolidate all readiness work into a national distributed architecture plan (multi-region/multi-branch scaling blueprint).',
            'why_this_order' => 'National architecture plan must come after all readiness/design sprints and before RC consolidation.',
            'allowed_scope' => [
                'distributed topology + data locality plan',
                'consistency/latency trade-off analysis',
                'phased national rollout blueprint',
            ],
            'out_of_scope' => ['executing national rollout', 'production distributed migration'],
            'production_safety_rule' => 'Plan/design only; no production distributed migration in NDA-1.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['national distributed architecture plan documented', 'depends-on readiness sprints GO', 'foundation GO preserved'],
            'watch_criteria' => ['plan complete but pending stakeholder sign-off'],
            'no_go_criteria' => ['production distributed migration attempted', 'foundation GO regressed'],
            'deliverables' => ['national distributed architecture plan', 'phased rollout blueprint', 'evidence doc'],
        ],
        [
            'id' => 'RC-1',
            'title' => 'Foundation Green Release Candidate Consolidation',
            'status' => 'planned',
            'priority' => 37,
            'depends_on' => [
                'NSF-9', 'NSF-10', 'CACHE-1', 'QUEUE-1', 'DBPERF-1', 'DBPERF-2',
                'RPT-1', 'STORAGE-1', 'STATELESS-1', 'LB-1', 'REPLICA-1',
                'CACHE-1-REDIS-READINESS', 'OBS-1', 'OBS-2', 'ROADMAP-1-CANONICALIZATION',
                'ENT-0', 'ENT-16',
                'PART-1', 'SEARCH-1', 'NDA-1',
            ],
            'category' => 'release_candidate',
            'is_release_candidate' => true,
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Consolidate all foundation expansion sprints into a green Release Candidate with a single validated GO across DQ/DMO/NSF/Combined + roadmap.',
            'why_this_order' => 'RC-1 must be LAST — after every planned foundation expansion sprint is GO.',
            'allowed_scope' => [
                'consolidated foundation GO evidence',
                'RC tag + release notes',
                'full gate run (DQ/DMO/NSF/Combined/roadmap)',
            ],
            'out_of_scope' => ['adding new foundation feature scope', 'any feature outside approved roadmap'],
            'production_safety_rule' => 'RC-1 consolidates only; no new destructive change; additive deploy only.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined', 'roadmap'],
            'go_criteria' => [
                'all expansion sprints GO',
                'DQ/DMO/NSF/Combined/roadmap all GO',
                'RC evidence consolidated',
            ],
            'watch_criteria' => ['one or more expansion sprints in WATCH with documented owner sign-off'],
            'no_go_criteria' => ['any expansion sprint NO-GO', 'foundation GO regressed'],
            'deliverables' => ['consolidated RC evidence', 'RC tag + release notes'],
        ],
    ],

    /**
     * Dependency map (human-readable, mirrored by `depends_on` above and validated
     * by FoundationRoadmapService).
     */
    'dependency_map' => [
        'feature_flag_before_risky_runtime' => 'NSF-9 before CACHE-1/QUEUE-1/DBPERF-2',
        'automated_smoke_before_stateful' => 'NSF-9 before Redis/Queue/PgBouncer',
        'cache_before_read_replica' => 'CACHE-1 before REPLICA-1',
        'queue_outbox_before_async' => 'QUEUE-1 before async integrations',
        'index_audit_before_tuning' => 'DBPERF-1 before DBPERF-2',
        'rpt_before_materialized_view' => 'RPT-1 summary before materialized view expansion',
        'object_storage_before_stateless' => 'STORAGE-1 before STATELESS-1',
        'stateless_before_load_balancer' => 'STATELESS-1 before LB-1',
        'load_balancer_before_replica_routing' => 'LB-1 before REPLICA-1 production routing',
        'partitioning_design_before_production' => 'PART-1 design before any partition production migration',
        'national_plan_before_rc' => 'NDA-1 before RC-1',
        'rc_after_all_expansion' => 'RC-1 after all planned foundation expansion sprints',
    ],

    'guardrails' => [
        'no_direct_production_partitioning_in_part1',
        'no_replica_read_routing_without_explicit_approval',
        'no_redis_cache_for_critical_mutable_values_without_invalidation_tests',
        'no_queue_job_without_idempotency_key_or_retry_failure_policy',
        'no_object_storage_migration_without_local_backup_and_rollback_plan',
        'no_load_balancer_pilot_until_stateless_readiness_go',
        'no_pgbouncer_production_routing_without_connection_pool_rollback_plan',
        'no_search_or_log_explorer_exposing_pii_or_secrets',
        'no_feature_outside_approved_roadmap_without_roadmap_update_sprint',
        'no_new_scope_outside_enterprise_freeze_areas_until_enterprise_foundation_go',
    ],
];
