<?php

/**
 * ROADMAP-1 — National Foundation Expansion Roadmap (source-locked).
 *
 * Canonical machine-readable roadmap consumed by:
 *  - App\Services\Architecture\FoundationRoadmapService (validation)
 *  - architecture:foundation-roadmap-check (governance command)
 *  - architecture:foundation-governance-summary (ROADMAP section)
 *
 * Companion doc: docs/architecture/national-foundation-expansion-roadmap.md
 *
 * RULES:
 *  - This file is the source of truth for foundation sequencing.
 *  - Future foundation sprints MUST follow `approved_sequence`.
 *  - Any change to order/scope requires an explicit ROADMAP update sprint + evidence doc.
 *  - This sprint (ROADMAP-1) only locks roadmap/sequencing/governance — no foundation
 *    feature is implemented here.
 */
return [
    'roadmap_id' => 'ROADMAP-1',
    'title' => 'National Foundation Expansion Roadmap Source Lock',
    'source_locked' => true,
    'active_track' => 'foundation_expansion',

    'current_baseline' => [
        'dq' => 'GO',
        'dq1' => 'GO',
        'dq2' => 'GO',
        'dq3' => 'GO',
        'dq3_1' => 'GO',
        'dmo' => 'GO',
        'nsf_raw' => 'GO',
        'nsf_effective' => 'GO',
        'combined_foundation' => 'GO',
        'node_runtime' => '>=20',
        'observability' => 'validated',
        'ci_evidence_gates' => 'automated',
        'baseline_sprint' => 'NSF-8',
    ],

    'principles' => [
        'foundation_before_feature_scale',
        'one_foundation_per_scoped_sprint',
        'readiness_or_design_first_for_risky_infra',
        'no_production_destructive_changes',
        'preserve_dq_dmo_nsf_combined_go',
        'every_sprint_updates_evidence_docs',
        'every_sprint_runs_test_pint_graphify',
        'every_deploy_backs_up_db_first',
        'every_production_deploy_runs_dq_dmo_nsf_foundation_gates',
    ],

    'rules' => [
        'future_sprints_must_follow_sequence' => true,
        'roadmap_change_requires_roadmap_update_sprint' => true,
        'preserve_foundation_go' => true,
        'rc_must_be_last' => true,
        'no_production_partitioning_in_part1' => true,
        'no_replica_read_routing_without_approval' => true,
        'no_lb_pilot_before_stateless_go' => true,
    ],

    /**
     * Approved sprint sequence. `priority` = stable execution order (ascending).
     * The very last item (highest priority) must be the RC consolidation.
     */
    'approved_sequence' => [
        [
            'id' => 'NSF-9',
            'title' => 'Release Safety, Feature Flag & Automated Smoke',
            'status' => 'completed',
            'priority' => 1,
            'depends_on' => ['NSF-8'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Lock release safety by adding a governed feature-flag layer and an automated post-deploy smoke suite so every future foundation sprint can be rolled out behind a flag and verified automatically.',
            'why_this_order' => 'Feature flags and automated smoke must exist before any risky runtime feature (Redis, Queue, PgBouncer) so those can be flag-gated and smoke-verified.',
            'allowed_scope' => [
                'feature flag registry + resolver (config/db-backed, no external SaaS)',
                'automated smoke command/suite runnable locally and in CI/VPS',
                'documentation of rollout/rollback via flags',
            ],
            'out_of_scope' => [
                'enabling Redis/Queue/PgBouncer',
                'any destructive migration',
                'external feature-flag SaaS dependency',
            ],
            'production_safety_rule' => 'Flags default OFF; smoke is read-only and must not mutate financial/inventory data.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'feature flag layer present and default-off',
                'automated smoke suite green locally and in CI',
                'DQ/DMO/NSF/Combined remain GO',
            ],
            'watch_criteria' => [
                'smoke suite partial coverage documented as backlog',
                'flag registry present but rollback playbook incomplete',
            ],
            'no_go_criteria' => [
                'flags default ON',
                'smoke mutates production data',
                'foundation GO regressed',
            ],
            'deliverables' => [
                'feature flag config/service',
                'automated smoke command',
                'evidence doc',
            ],
        ],
        [
            'id' => 'NSF-10',
            'title' => 'Observability, Backup & Release Safety Hardening',
            'status' => 'completed',
            'priority' => 2,
            'depends_on' => ['NSF-9'],
            'category' => 'release_safety',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Harden observability, backup verification, and release-safety runbooks building on NSF-9 flags/smoke.',
            'why_this_order' => 'Observability and backup hardening must precede stateful infra (cache/queue/db tuning) so regressions are detectable and recoverable.',
            'allowed_scope' => [
                'backup verification runbook + restore drill doc',
                'observability metric/log coverage expansion (no PII)',
                'release safety checklist automation',
            ],
            'out_of_scope' => [
                'enabling caching/queue backends',
                'exposing PII/secrets in logs/metrics',
            ],
            'production_safety_rule' => 'Backups verified before any future stateful rollout; no secrets/PII in observability output.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'backup + restore drill documented and evidenced',
                'observability coverage expanded without PII',
                'foundation GO preserved',
            ],
            'watch_criteria' => ['restore drill deferred to next window with owner sign-off'],
            'no_go_criteria' => ['PII/secrets in logs', 'no verified backup path'],
            'deliverables' => ['backup verification runbook', 'observability hardening', 'evidence doc'],
        ],
        [
            'id' => 'CACHE-1',
            'title' => 'Cache Strategy, Redis Readiness & Invalidation Governance',
            'status' => 'completed',
            'priority' => 3,
            'depends_on' => ['NSF-9'],
            'category' => 'cache',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_invalidation_rules' => true,
            'disambiguation_note' => 'This is the earlier design-only cache strategy/invalidation-governance sprint (governance section: cache_governance). See CACHE-1-REDIS-READINESS (priority 12) for the later Redis shared cache/session runtime-readiness sprint (cache_redis_governance) — do not conflate the two.',
            'objective' => 'Define the cache strategy and Redis readiness with a mandatory invalidation governance model before any critical value is cached.',
            'why_this_order' => 'Cache readiness (with invalidation tests) is prerequisite for read-replica usefulness and comes after feature-flag/smoke so it can be flag-gated and verified.',
            'allowed_scope' => [
                'cache key taxonomy + TTL policy',
                'invalidation rules + tests for cached values',
                'Redis readiness/config design (not enabling critical caching)',
            ],
            'out_of_scope' => [
                'caching critical mutable financial/inventory values without invalidation tests',
                'making Redis a hard runtime dependency for core flows',
            ],
            'production_safety_rule' => 'No Redis cache for critical mutable financial/inventory values without invalidation tests.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'invalidation rules documented and tested',
                'cache taxonomy + TTL policy locked',
                'foundation GO preserved',
            ],
            'watch_criteria' => ['non-critical cache candidates deferred with backlog note'],
            'no_go_criteria' => [
                'critical financial/inventory value cached without invalidation test',
                'foundation GO regressed',
            ],
            'deliverables' => ['cache strategy doc', 'invalidation rules + tests', 'evidence doc'],
        ],
        [
            'id' => 'QUEUE-1',
            'title' => 'Queue, Idempotency & Outbox Foundation',
            'status' => 'completed',
            'priority' => 4,
            'depends_on' => ['NSF-9', 'CACHE-1'],
            'category' => 'queue',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_idempotency_rules' => true,
            'requires_outbox_rules' => true,
            'objective' => 'Establish the queue foundation with mandatory idempotency keys and an outbox pattern so async integrations are safe and replayable.',
            'why_this_order' => 'Queue/outbox must exist before any async integration; depends on cache readiness and feature-flag/smoke for safe rollout.',
            'allowed_scope' => [
                'queue design + idempotency key convention',
                'outbox table/design for reliable async dispatch',
                'retry/failure policy definition',
            ],
            'out_of_scope' => [
                'auto-sending WhatsApp',
                'auto-creating LabOrder from RME payment',
                'queue jobs without idempotency key or retry/failure policy',
            ],
            'production_safety_rule' => 'No queue job without idempotency key or retry/failure policy.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => [
                'idempotency key convention enforced',
                'outbox pattern documented + tested',
                'retry/failure policy defined',
            ],
            'watch_criteria' => ['outbox adopted for subset of integrations, remainder backlogged'],
            'no_go_criteria' => ['job without idempotency/retry policy', 'foundation GO regressed'],
            'deliverables' => ['queue+outbox design', 'idempotency convention', 'evidence doc'],
        ],
        [
            'id' => 'DBPERF-1',
            'title' => 'PostgreSQL Index Optimization & Query Plan Audit',
            'status' => 'completed',
            'priority' => 5,
            'depends_on' => ['NSF-9'],
            'category' => 'db_performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Audit query plans and optimize indexes with additive, non-destructive migrations before connection pooling/runtime tuning.',
            'why_this_order' => 'Index audit must precede PgBouncer/runtime tuning so pooling is applied to an already-optimized workload.',
            'allowed_scope' => [
                'EXPLAIN/query-plan audit',
                'additive index migrations (no drops/rewrites of hot tables in production without plan)',
                'slow-query documentation',
            ],
            'out_of_scope' => ['destructive schema rewrites', 'partitioning production migration'],
            'production_safety_rule' => 'Index changes are additive; no migrate:fresh/db:wipe; large index builds planned for low-traffic window.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['query plan audit documented', 'additive indexes validated', 'foundation GO preserved'],
            'watch_criteria' => ['some index candidates deferred to low-traffic window'],
            'no_go_criteria' => ['destructive schema change', 'foundation GO regressed'],
            'deliverables' => ['query plan audit', 'index migrations', 'evidence doc'],
        ],
        [
            'id' => 'DBPERF-2',
            'title' => 'PgBouncer & PostgreSQL Runtime Tuning',
            'status' => 'completed',
            'priority' => 6,
            'depends_on' => ['DBPERF-1'],
            'category' => 'db_performance',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_rollback_plan' => true,
            'objective' => 'Design PgBouncer connection pooling and PostgreSQL runtime tuning with an explicit connection-pool rollback plan.',
            'why_this_order' => 'Follows index audit so pooling/tuning target an optimized workload; readiness-first with rollback plan.',
            'allowed_scope' => [
                'PgBouncer pool sizing/mode design',
                'PostgreSQL runtime parameter tuning proposal',
                'connection-pool rollback plan',
            ],
            'out_of_scope' => ['production PgBouncer routing without rollback plan'],
            'production_safety_rule' => 'No PgBouncer production routing without connection pool rollback plan.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['pool design + rollback plan documented', 'tuning proposal evidenced', 'foundation GO preserved'],
            'watch_criteria' => ['pilot pooling on non-critical path only'],
            'no_go_criteria' => ['production routing without rollback plan', 'foundation GO regressed'],
            'deliverables' => ['PgBouncer design', 'runtime tuning proposal', 'rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'RPT-1',
            'title' => 'Materialized View + rpt_* Summary Foundation',
            'status' => 'completed',
            'priority' => 7,
            'depends_on' => ['DBPERF-2'],
            'category' => 'reporting',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Introduce rpt_* summary tables first, then materialized views, so reporting reads move off transactional tables safely.',
            'why_this_order' => 'rpt_* summary must precede materialized view expansion; follows index audit for efficient refresh.',
            'allowed_scope' => [
                'rpt_* summary table design + refresh strategy',
                'materialized view design/readiness (additive, evidence-based)',
                'feature-flag gated future read-path routing for reports',
            ],
            'out_of_scope' => ['destructive replacement of transactional tables', 'exposing KTP/NIK in summaries'],
            'production_safety_rule' => 'Additive rpt_* only; no KTP/NIK in summaries; refresh must not lock hot tables.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['rpt_* summary foundation documented + tested', 'materialized view design locked', 'foundation GO preserved'],
            'watch_criteria' => ['materialized view rollout phased'],
            'no_go_criteria' => ['PII in summaries', 'foundation GO regressed'],
            'deliverables' => ['rpt_* governance config', 'materialized view readiness policy', 'dry-run refresh command', 'evidence doc'],
        ],
        [
            'id' => 'STORAGE-1',
            'title' => 'Object Storage Readiness',
            'status' => 'completed',
            'priority' => 8,
            'depends_on' => ['NSF-10'],
            'category' => 'storage',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'requires_rollback_plan' => true,
            'governance_section' => 'storage_governance',
            'readiness_command' => 'storage:object-readiness-check',
            'go_tag' => 'storage-1-object-storage-readiness-go',
            'go_commit' => 'd8a9c73',
            'objective' => 'Prepare object storage (S3-compatible) readiness for uploaded assets so the app can become stateless.',
            'why_this_order' => 'Object storage must precede stateless/load balancer because local-disk assets block horizontal scaling.',
            'allowed_scope' => [
                'object storage driver readiness/config design',
                'asset migration plan with local backup + rollback',
                'private/signed URL handling for sensitive docs',
            ],
            'out_of_scope' => [
                'object storage migration without local backup and rollback plan',
                'exposing KTP/NIK/scanned docs publicly',
            ],
            'production_safety_rule' => 'No object storage migration without local backup and rollback plan; sensitive docs stay private.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['storage readiness + migration/rollback plan documented', 'sensitive-doc privacy preserved', 'foundation GO preserved'],
            'watch_criteria' => ['migration executed for subset of buckets'],
            'no_go_criteria' => ['no rollback plan', 'public exposure of sensitive docs', 'foundation GO regressed'],
            'deliverables' => ['object storage readiness doc', 'migration/rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'STATELESS-1',
            'title' => 'Stateless App Readiness',
            'status' => 'completed',
            'priority' => 9,
            'depends_on' => ['STORAGE-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'stateless_governance',
            'readiness_command' => 'runtime:stateless-readiness-check',
            'go_tag' => 'stateless-1-runtime-statelessness-deploy-portability-foundation-go',
            'go_commit' => 'c0cff0c',
            'objective' => 'Make the app stateless (session/cache/queue/storage externalized) so multiple instances can run behind a load balancer.',
            'why_this_order' => 'Depends on object storage; must be GO before the load balancer pilot.',
            'allowed_scope' => [
                'externalized session/cache/file storage readiness',
                'stateless readiness checklist + audit',
                'sticky-session removal design',
            ],
            'out_of_scope' => ['starting the load balancer pilot', 'local-disk session/asset dependencies'],
            'production_safety_rule' => 'Stateless readiness must be GO before LB-1; no local-only state on request path.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['stateless readiness audit passes', 'no local-only request state', 'foundation GO preserved'],
            'watch_criteria' => ['residual local state documented as backlog'],
            'no_go_criteria' => ['request-path local state remains', 'foundation GO regressed'],
            'deliverables' => ['stateless readiness audit', 'externalization design', 'evidence doc'],
        ],
        [
            'id' => 'LB-1',
            'title' => 'Load Balancer Pilot',
            'status' => 'completed',
            'priority' => 10,
            'depends_on' => ['STATELESS-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'lb_governance',
            'readiness_command' => 'lb:readiness-check',
            'go_tag' => 'lb-1-load-balancer-pilot-go',
            'go_commit' => '1be6f50',
            'objective' => 'Pilot a load balancer in front of stateless app instances, gated on STATELESS-1 GO.',
            'why_this_order' => 'Load balancer requires stateless readiness and precedes read-replica production routing.',
            'allowed_scope' => [
                'load balancer pilot design (health checks, draining)',
                'multi-instance pilot on non-production or gated path',
                'failover/rollback plan',
            ],
            'out_of_scope' => ['LB pilot before stateless readiness GO', 'routing read traffic to replica'],
            'production_safety_rule' => 'No load balancer pilot until stateless readiness is GO.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['LB pilot validated with health checks + rollback', 'STATELESS-1 GO confirmed', 'foundation GO preserved'],
            'watch_criteria' => ['pilot limited to staging/gated traffic'],
            'no_go_criteria' => ['stateless not GO', 'foundation GO regressed'],
            'deliverables' => ['LB pilot design', 'failover/rollback plan', 'evidence doc'],
        ],
        [
            'id' => 'REPLICA-1',
            'title' => 'Read Replica Readiness',
            'status' => 'completed',
            'priority' => 11,
            'depends_on' => ['LB-1', 'CACHE-1'],
            'category' => 'scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'readiness_only' => true,
            'governance_section' => 'database_replica_governance',
            'readiness_command' => 'db:replica-readiness-check',
            'go_tag' => 'replica-1-read-replica-readiness-database-scale-foundation-go',
            'go_commit' => 'bca0f645e22da091b14cf03bb83b74c9c5449c98',
            'objective' => 'Prepare read-replica readiness (replication + read/write split design) WITHOUT routing production read traffic to the replica unless explicitly approved.',
            'why_this_order' => 'Read replica follows cache (offload) and load balancer (routing capability); readiness-only until approved.',
            'allowed_scope' => [
                'replication topology + lag monitoring design',
                'read/write connection split design',
                'read-consistency risk analysis',
            ],
            'out_of_scope' => [
                'routing production read traffic to replica without explicit approval',
                'stale-read-sensitive financial/inventory reads on replica',
            ],
            'production_safety_rule' => 'No read traffic redirected to replica unless explicitly approved.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['replica readiness + read/write split design documented', 'no production read routing enabled', 'foundation GO preserved'],
            'watch_criteria' => ['replica provisioned but routing kept off pending approval'],
            'no_go_criteria' => ['production reads routed to replica without approval', 'foundation GO regressed'],
            'deliverables' => ['replica readiness design', 'read/write split design', 'evidence doc'],
        ],
        [
            'id' => 'CACHE-1-REDIS-READINESS',
            'title' => 'Redis Shared Cache & Session Readiness',
            'status' => 'completed',
            'priority' => 12,
            'depends_on' => ['REPLICA-1'],
            'category' => 'cache',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'disambiguates' => 'CACHE-1',
            'disambiguation_note' => 'Distinct from CACHE-1 (Cache Strategy, Redis Readiness & Invalidation Governance, priority 3) which was the earlier design-only cache/invalidation governance sprint. This entry is the later Redis shared cache + session runtime-readiness sprint (cache_redis_governance).',
            'governance_section' => 'cache_redis_governance',
            'readiness_command' => 'cache:redis-readiness-check',
            'go_tag' => 'cache-1-redis-shared-cache-session-readiness-go',
            'go_commit' => 'be9c2d7',
            'objective' => 'Prepare Redis-backed shared cache and session readiness (config/env only) distinct from the earlier CACHE-1 invalidation-governance design sprint.',
            'why_this_order' => 'Runs after REPLICA-1 readiness in the actual delivery sequence; readiness/config-only, no forced runtime driver change.',
            'allowed_scope' => ['Redis cache/session readiness config', 'redis readiness check command', 'governance rules'],
            'out_of_scope' => ['forcing Redis as the production cache/session driver', 'critical financial/inventory caching without invalidation tests'],
            'production_safety_rule' => 'Redis readiness is opt-in via config; no runtime driver forced by this sprint.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['redis readiness command GO', 'cache_redis_governance rules published', 'foundation GO preserved'],
            'watch_criteria' => ['redis not yet the active driver on VPS pilot'],
            'no_go_criteria' => ['critical value cached without invalidation test', 'foundation GO regressed'],
            'deliverables' => ['cache_redis_governance rules', 'redis readiness command', 'evidence doc'],
        ],
        [
            'id' => 'OBS-1',
            'title' => 'Request ID, Correlation ID & Observability Foundation',
            'status' => 'completed',
            'priority' => 13,
            'depends_on' => ['CACHE-1-REDIS-READINESS'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'governance_section' => 'observability_governance',
            'readiness_command' => 'obs:readiness-check',
            'go_tag' => 'obs-1-request-id-correlation-observability-foundation-go',
            'go_commit' => 'df07d90',
            'objective' => 'Attach a bounded request/correlation id and PII-free log context to every request for cross-cutting traceability.',
            'why_this_order' => 'Observability/request-id foundation follows cache/replica readiness so future scale-out work is traceable.',
            'allowed_scope' => ['request/correlation id middleware', 'PII-free log context', 'readiness command'],
            'out_of_scope' => ['external monitoring vendor', 'log/session/cache/queue driver change'],
            'production_safety_rule' => 'No PII/secret in request/correlation id context; inbound ids only trusted when explicitly configured.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['observability readiness command GO', 'request id header present', 'foundation GO preserved'],
            'watch_criteria' => ['multi-node id propagation deferred to LB/REPLICA scale-out'],
            'no_go_criteria' => ['PII/secret exposed in log context', 'foundation GO regressed'],
            'deliverables' => ['observability_governance rules', 'request correlation middleware', 'evidence doc'],
        ],
        [
            'id' => 'OBS-2',
            'title' => 'Centralized Logging & Error Tracking Readiness',
            'status' => 'completed',
            'priority' => 14,
            'depends_on' => ['OBS-1'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'governance_section' => 'observability_pipeline_governance',
            'readiness_command' => 'obs:pipeline-readiness-check',
            'go_tag' => 'obs-2-centralized-logging-error-tracking-readiness-go',
            'go_commit' => '5cb632c',
            'objective' => 'Prepare readiness (config/rules only) for a future centralized log collector and error tracker, OFF by default.',
            'why_this_order' => 'Centralized logging/error-tracking readiness follows the OBS-1 request/correlation id foundation it depends on for event correlation.',
            'allowed_scope' => ['central logging/error tracking readiness config', 'readiness command', 'governance rules'],
            'out_of_scope' => ['installing an external monitoring vendor', 'sending PII/log traffic externally'],
            'production_safety_rule' => 'Central logging/error tracking stay OFF by default; no PII/secret ever exported.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['pipeline readiness command GO', 'PII-send risk check enforced', 'foundation GO preserved'],
            'watch_criteria' => ['no external vendor connected yet — readiness only'],
            'no_go_criteria' => ['PII/secret sent externally', 'foundation GO regressed'],
            'deliverables' => ['observability_pipeline_governance rules', 'pipeline readiness command', 'evidence doc'],
        ],
        [
            'id' => 'ROADMAP-1-CANONICALIZATION',
            'title' => 'Foundation Roadmap Canonicalization',
            'status' => 'completed',
            'priority' => 15,
            'depends_on' => ['OBS-2'],
            'category' => 'governance',
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'disambiguates' => 'ROADMAP-1',
            'disambiguation_note' => 'Distinct from the top-level roadmap_id ROADMAP-1 (this file\'s own original source-lock identity, tag roadmap-1-national-foundation-expansion-source-lock-go). This entry is the later canonicalization sprint that re-synced completed/next status after STORAGE-1..OBS-2.',
            'governance_section' => 'roadmap_governance',
            'readiness_command' => 'foundation:roadmap-check',
            'go_tag' => 'roadmap-1-foundation-roadmap-canonicalization-go',
            'objective' => 'Canonicalize this roadmap so completed/next status matches actual delivered foundation sprints (STORAGE-1..OBS-2), never pointing next_recommended_sprint back at a completed sprint.',
            'why_this_order' => 'Canonicalization must run after the sprints it reconciles (OBS-2) so it can correct their recorded status in one pass.',
            'allowed_scope' => ['roadmap config staleness fixes', 'roadmap governance rules', 'roadmap check command', 'docs'],
            'out_of_scope' => ['runtime driver change', 'business workflow change', 'new external dependency'],
            'production_safety_rule' => 'Governance/config/docs only; no runtime driver, migration, or workflow change.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['roadmap check command GO', 'next_recommended_sprint not stale', 'foundation GO preserved'],
            'watch_criteria' => ['legacy pre-STORAGE-1 sprints not retrofitted with go_tag metadata'],
            'no_go_criteria' => ['next_recommended_sprint points at a completed sprint', 'foundation GO regressed'],
            'deliverables' => ['foundation_roadmap.php canonicalization', 'roadmap_governance rules', 'foundation:roadmap-check command', 'evidence doc'],
        ],
        [
            'id' => 'MON-1',
            'title' => 'Health Monitoring, Alerting & Uptime Readiness',
            'status' => 'planned',
            'priority' => 16,
            'depends_on' => ['ROADMAP-1-CANONICALIZATION'],
            'category' => 'observability',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Prepare health-monitoring, alerting, and uptime readiness (design/config first) building on OBS-1/OBS-2 and the LB-1 health endpoint.',
            'why_this_order' => 'Monitoring/alerting readiness is the natural next step after request correlation and centralized logging/error-tracking readiness are in place.',
            'allowed_scope' => ['uptime/health-check readiness design', 'alerting threshold design (no external paging vendor required)', 'readiness command'],
            'out_of_scope' => ['external paging/on-call vendor integration without review', 'PII/secret in alerts'],
            'production_safety_rule' => 'No external alerting vendor without a privacy/rollback review; no PII/secret in alert payloads.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['monitoring/alerting readiness documented', 'foundation GO preserved'],
            'watch_criteria' => ['external alerting vendor deferred pending review'],
            'no_go_criteria' => ['PII/secret in alert payload', 'foundation GO regressed'],
            'deliverables' => ['monitoring readiness design', 'evidence doc'],
        ],
        [
            'id' => 'PART-1',
            'title' => 'Partitioning Design, Not Production Yet',
            'status' => 'planned',
            'priority' => 17,
            'depends_on' => ['DBPERF-1', 'RPT-1'],
            'category' => 'db_scaling',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'production_forbidden' => true,
            'objective' => 'Design table partitioning strategy (range/list keys, migration path) as DESIGN ONLY — no production partition migration.',
            'why_this_order' => 'Partitioning design follows index audit and rpt_* summary; production migration is explicitly deferred.',
            'allowed_scope' => [
                'partition key + strategy design',
                'zero-downtime partition migration plan (design only)',
                'candidate table analysis',
            ],
            'out_of_scope' => [
                'any production partitioning migration',
                'destructive table rewrite',
            ],
            'production_safety_rule' => 'No direct production partitioning in PART-1; design/plan only.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['partition strategy + migration plan documented', 'no production partition migration performed', 'foundation GO preserved'],
            'watch_criteria' => ['candidate tables identified, plan pending review'],
            'no_go_criteria' => ['production partition migration attempted', 'foundation GO regressed'],
            'deliverables' => ['partitioning design', 'zero-downtime migration plan', 'evidence doc'],
        ],
        [
            'id' => 'SEARCH-1',
            'title' => 'Search Engine & Log Explorer Foundation',
            'status' => 'planned',
            'priority' => 18,
            'depends_on' => ['NSF-10', 'QUEUE-1'],
            'category' => 'search',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Introduce a search engine and log explorer foundation (indexing pipeline design) without exposing PII or secrets.',
            'why_this_order' => 'Search/log explorer follows observability hardening and queue (for async indexing).',
            'allowed_scope' => [
                'search index schema + async indexing design (via QUEUE-1)',
                'log explorer readiness with PII/secret redaction',
                'access control for search/log surfaces',
            ],
            'out_of_scope' => [
                'search/log explorer exposing PII/secrets',
                'indexing KTP/NIK/raw medical notes',
            ],
            'production_safety_rule' => 'No search/log explorer exposing PII/secrets.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['search/log design with redaction documented', 'access control defined', 'foundation GO preserved'],
            'watch_criteria' => ['indexing scope limited to non-sensitive fields initially'],
            'no_go_criteria' => ['PII/secrets indexed or exposed', 'foundation GO regressed'],
            'deliverables' => ['search foundation design', 'log explorer readiness', 'evidence doc'],
        ],
        [
            'id' => 'NDA-1',
            'title' => 'National Distributed Architecture Plan',
            'status' => 'planned',
            'priority' => 19,
            'depends_on' => ['REPLICA-1', 'LB-1', 'PART-1', 'STORAGE-1', 'SEARCH-1'],
            'category' => 'architecture',
            'may_touch_production_infra' => false,
            'requires_design_first' => true,
            'objective' => 'Consolidate all readiness work into a national distributed architecture plan (multi-region/multi-branch scaling blueprint).',
            'why_this_order' => 'National architecture plan must come after all readiness/design sprints and before RC consolidation.',
            'allowed_scope' => [
                'distributed topology + data locality plan',
                'consistency/latency trade-off analysis',
                'phased national rollout blueprint',
            ],
            'out_of_scope' => ['executing national rollout', 'production distributed migration'],
            'production_safety_rule' => 'Plan/design only; no production distributed migration in NDA-1.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined'],
            'go_criteria' => ['national distributed architecture plan documented', 'depends-on readiness sprints GO', 'foundation GO preserved'],
            'watch_criteria' => ['plan complete but pending stakeholder sign-off'],
            'no_go_criteria' => ['production distributed migration attempted', 'foundation GO regressed'],
            'deliverables' => ['national distributed architecture plan', 'phased rollout blueprint', 'evidence doc'],
        ],
        [
            'id' => 'RC-1',
            'title' => 'Foundation Green Release Candidate Consolidation',
            'status' => 'planned',
            'priority' => 20,
            'depends_on' => [
                'NSF-9', 'NSF-10', 'CACHE-1', 'QUEUE-1', 'DBPERF-1', 'DBPERF-2',
                'RPT-1', 'STORAGE-1', 'STATELESS-1', 'LB-1', 'REPLICA-1',
                'CACHE-1-REDIS-READINESS', 'OBS-1', 'OBS-2', 'ROADMAP-1-CANONICALIZATION',
                'PART-1', 'SEARCH-1', 'NDA-1',
            ],
            'category' => 'release_candidate',
            'is_release_candidate' => true,
            'may_touch_production_infra' => false,
            'requires_design_first' => false,
            'objective' => 'Consolidate all foundation expansion sprints into a green Release Candidate with a single validated GO across DQ/DMO/NSF/Combined + roadmap.',
            'why_this_order' => 'RC-1 must be LAST — after every planned foundation expansion sprint is GO.',
            'allowed_scope' => [
                'consolidated foundation GO evidence',
                'RC tag + release notes',
                'full gate run (DQ/DMO/NSF/Combined/roadmap)',
            ],
            'out_of_scope' => ['adding new foundation feature scope', 'any feature outside approved roadmap'],
            'production_safety_rule' => 'RC-1 consolidates only; no new destructive change; additive deploy only.',
            'required_gates' => ['test', 'pint', 'graphify', 'dq', 'dmo', 'nsf', 'combined', 'roadmap'],
            'go_criteria' => [
                'all expansion sprints GO',
                'DQ/DMO/NSF/Combined/roadmap all GO',
                'RC evidence consolidated',
            ],
            'watch_criteria' => ['one or more expansion sprints in WATCH with documented owner sign-off'],
            'no_go_criteria' => ['any expansion sprint NO-GO', 'foundation GO regressed'],
            'deliverables' => ['consolidated RC evidence', 'RC tag + release notes'],
        ],
    ],

    /**
     * Dependency map (human-readable, mirrored by `depends_on` above and validated
     * by FoundationRoadmapService).
     */
    'dependency_map' => [
        'feature_flag_before_risky_runtime' => 'NSF-9 before CACHE-1/QUEUE-1/DBPERF-2',
        'automated_smoke_before_stateful' => 'NSF-9 before Redis/Queue/PgBouncer',
        'cache_before_read_replica' => 'CACHE-1 before REPLICA-1',
        'queue_outbox_before_async' => 'QUEUE-1 before async integrations',
        'index_audit_before_tuning' => 'DBPERF-1 before DBPERF-2',
        'rpt_before_materialized_view' => 'RPT-1 summary before materialized view expansion',
        'object_storage_before_stateless' => 'STORAGE-1 before STATELESS-1',
        'stateless_before_load_balancer' => 'STATELESS-1 before LB-1',
        'load_balancer_before_replica_routing' => 'LB-1 before REPLICA-1 production routing',
        'partitioning_design_before_production' => 'PART-1 design before any partition production migration',
        'national_plan_before_rc' => 'NDA-1 before RC-1',
        'rc_after_all_expansion' => 'RC-1 after all planned foundation expansion sprints',
    ],

    'guardrails' => [
        'no_direct_production_partitioning_in_part1',
        'no_replica_read_routing_without_explicit_approval',
        'no_redis_cache_for_critical_mutable_values_without_invalidation_tests',
        'no_queue_job_without_idempotency_key_or_retry_failure_policy',
        'no_object_storage_migration_without_local_backup_and_rollback_plan',
        'no_load_balancer_pilot_until_stateless_readiness_go',
        'no_pgbouncer_production_routing_without_connection_pool_rollback_plan',
        'no_search_or_log_explorer_exposing_pii_or_secrets',
        'no_feature_outside_approved_roadmap_without_roadmap_update_sprint',
    ],
];
