<?php

/**
 * NSF-6 application-level national scale foundation rules.
 * Machine-readable governance — validated by architecture:nsf-governance-check.
 */
return [
    'version' => 'NSF-6',
    'sprint' => 'NSF-6',

    'rules' => [
        [
            'rule_id' => 'NSF-R001',
            'title' => 'Branch isolation required',
            'severity' => 'error',
            'description' => 'Every branch-scoped operational entity/query/report must respect BranchContext or explicit authorized branch filter.',
            'applies_to' => ['branch_scoped_entities', 'reports', 'dashboards'],
            'validation' => 'branch_isolation_declared',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R002',
            'title' => 'Inventory stock is ledger-derived only',
            'severity' => 'error',
            'description' => 'Current stock must be derived from trx_inventory_movements aggregation.',
            'applies_to' => ['inventory', 'reports'],
            'validation' => 'inventory_ledger_derived',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R003',
            'title' => 'No mutable stock columns',
            'severity' => 'error',
            'description' => 'Do not introduce or depend on mutable stock quantity columns for canonical stock.',
            'applies_to' => ['inventory', 'migrations'],
            'validation' => 'no_mutable_stock_columns',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R004',
            'title' => 'Inventory movement is source of truth',
            'severity' => 'error',
            'description' => 'Purchase, transfer, adjustment, stock opname, batch/expiry movement impact must flow through movement ledger.',
            'applies_to' => ['inventory', 'workflows'],
            'validation' => 'movement_ledger_workflows',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R005',
            'title' => 'Safe index governance',
            'severity' => 'warning',
            'description' => 'New index proposals must be justified by slow query audit, query plan, or documented performance evidence.',
            'applies_to' => ['migrations', 'performance'],
            'validation' => 'safe_index_governance',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R006',
            'title' => 'Migration safety',
            'severity' => 'error',
            'description' => 'Migrations must be idempotent where possible, PostgreSQL-safe, and SQLite-test compatible when full suite uses SQLite.',
            'applies_to' => ['migrations'],
            'validation' => 'migration_safety',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R007',
            'title' => 'Driver-aware SQL',
            'severity' => 'error',
            'description' => 'Raw SQL must be DB-driver aware or guarded, especially PostgreSQL-specific syntax.',
            'applies_to' => ['commands', 'repositories'],
            'validation' => 'driver_aware_sql',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R008',
            'title' => 'Observability required',
            'severity' => 'error',
            'description' => 'Performance audit and runtime query observability commands must remain available.',
            'applies_to' => ['commands', 'performance'],
            'validation' => 'observability_commands_available',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R009',
            'title' => 'pg_stat guardrail',
            'severity' => 'warning',
            'description' => 'On VPS, pg_stat_statements should be available/preloaded for runtime query observability.',
            'applies_to' => ['performance', 'vps'],
            'validation' => 'pg_stat_statements_guardrail',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R010',
            'title' => 'Privacy-safe evidence',
            'severity' => 'error',
            'description' => 'Architecture/performance/governance command output must not expose PHI/PII or raw row-level financial detail.',
            'applies_to' => ['commands', 'evidence'],
            'validation' => 'privacy_safe_evidence',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R011',
            'title' => 'Full suite gate',
            'severity' => 'warning',
            'description' => 'Foundation sprints must preserve full suite green or document unrelated infra-only failure.',
            'applies_to' => ['process', 'ci'],
            'validation' => 'full_suite_gate',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R012',
            'title' => 'Build gate',
            'severity' => 'warning',
            'description' => 'npm build and pint/composer checks must pass before GO.',
            'applies_to' => ['process', 'ci'],
            'validation' => 'build_gate',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R013',
            'title' => 'Deploy backup gate',
            'severity' => 'error',
            'description' => 'VPS deploy must create pre-deploy DB backup and record path/size.',
            'applies_to' => ['deploy'],
            'validation' => 'deploy_backup_gate',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R014',
            'title' => 'Deploy smoke gate',
            'severity' => 'error',
            'description' => 'VPS deploy must smoke /login and protected routes; no 500 allowed.',
            'applies_to' => ['deploy'],
            'validation' => 'deploy_smoke_gate',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R015',
            'title' => 'No distributed technology before NDA approval',
            'severity' => 'error',
            'description' => 'Redis/Kafka/GraphQL/gRPC/NoSQL/LB/CDN/distributed ID must not be added without NDA sprint decision.',
            'applies_to' => ['dependencies', 'architecture'],
            'validation' => 'no_distributed_tech',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R016',
            'title' => 'DMO alignment required',
            'severity' => 'error',
            'description' => 'New reports/dashboards/KPIs must map to DMO canonical entities/metrics and pass DMO governance check.',
            'applies_to' => ['reports', 'dashboards', 'kpis'],
            'validation' => 'dmo_alignment_required',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R017',
            'title' => 'Owner KPI rule dependency',
            'severity' => 'error',
            'description' => 'Owner KPI changes must remain aligned with canonical Owner KPI registry.',
            'applies_to' => ['owner_kpis', 'dashboards'],
            'validation' => 'owner_kpi_registry_dependency',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R018',
            'title' => 'Read-only governance commands',
            'severity' => 'error',
            'description' => 'Architecture/governance validation commands must be read-only and must not mutate app data.',
            'applies_to' => ['commands'],
            'validation' => 'readonly_governance_commands',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R019',
            'title' => 'Rollback readiness',
            'severity' => 'warning',
            'description' => 'Every deployed foundation sprint must document rollback plan.',
            'applies_to' => ['process', 'deploy'],
            'validation' => 'rollback_readiness',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R020',
            'title' => 'Evidence path standard',
            'severity' => 'error',
            'description' => 'Every foundation sprint must output evidence under storage/app/architecture or storage/app/performance.',
            'applies_to' => ['evidence'],
            'validation' => 'evidence_path_standard',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R021',
            'title' => 'National scale readiness boundary',
            'severity' => 'info',
            'description' => 'NDA work may plan distributed architecture, but implementation must not violate branch isolation, ledger stock, DMO metrics, privacy, or deploy gates.',
            'applies_to' => ['architecture', 'nda'],
            'validation' => 'nda_readiness_boundary',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R023',
            'title' => 'Source-document batch linkage required',
            'severity' => 'error',
            'description' => 'Batch-tracked goods receipt, transfer, and opname items must have inventory_batch_id before finalize/movement creation.',
            'applies_to' => ['inventory', 'workflows'],
            'validation' => 'source_document_batch_linkage',
            'status' => 'active',
        ],
        [
            'rule_id' => 'NSF-R024',
            'title' => 'Ambiguous inventory batch linkage repair requires approved mapping',
            'severity' => 'error',
            'description' => 'Ambiguous transfer/opname source-document batch repair must use inventory:repair-ambiguous-batch-links with approval_reference, approved_by, approved_at, and reason. Dry-run before execute; audit log required.',
            'applies_to' => ['inventory', 'governance'],
            'validation' => 'ambiguous_batch_manual_repair',
            'status' => 'active',
        ],
    ],

    'deferred_warnings' => [
        'NSF-M001' => 'Full suite and build gates require manual CI/sprint evidence',
        'NSF-M002' => 'pg_stat_statements validated on VPS; local SQLite may be not_applicable',
    ],

    'governance_commands' => [
        'architecture:nsf-governance-check',
        'architecture:dmo-governance-check',
        'architecture:owner-kpi-registry',
        'architecture:dmo-foundation',
        'architecture:canonical-entity-inventory',
        'architecture:canonical-metric-reconciliation',
        'inventory:source-document-batch-audit',
        'inventory:backfill-source-document-batches',
        'inventory:ambiguous-batch-review-pack',
        'inventory:repair-ambiguous-batch-links',
    ],

    'observability_commands' => [
        'performance:slow-query-audit',
        'performance:runtime-query-observability',
    ],

    'deploy_gates' => [
        'pre_deploy_db_backup',
        'composer_install',
        'npm_build',
        'migrate_force',
        'dq1_audit',
        'dq2_audit',
        'dq3_audit',
        'dq2_backfill_dry_run',
        'dq3_backfill_dry_run',
        'cache_rebuild',
        'service_restart',
        'smoke_check',
    ],

    'forbidden_distributed_packages' => [
        'predis/predis',
        'phpredis/phpredis',
        'enqueue/rdkafka',
        'grpc/grpc',
        'mongodb/mongodb',
        'rebing/graphql-laravel',
    ],

    'mutable_stock_forbidden_tables' => [
        'mst_products',
        'inv_locations',
        'trx_inventory_batches',
        'trx_stock_opname_items',
    ],

    'mutable_stock_forbidden_columns' => [
        'current_stock',
        'qty_on_hand',
        'stock_balance',
        'balance_qty',
        'on_hand_qty',
    ],

    'movement_workflow_services' => [
        'App\\Modules\\Inventory\\Services\\GoodsReceiptService',
        'App\\Modules\\Inventory\\Services\\StockTransferService',
        'App\\Modules\\Inventory\\Services\\StockOpnameService',
        'App\\Modules\\Inventory\\Services\\InventoryStockService',
    ],

    'privacy_forbidden_terms' => [
        'ktp',
        'nik',
        'no_ktp',
        'phone_number',
        'alamat',
        'diagnosis',
        'odontogram_notes',
        'medical_notes',
        'patient_name',
    ],

    'evidence_roots' => [
        'storage/app/architecture',
        'storage/app/performance',
    ],
];
