<?php

declare(strict_types=1);

namespace App\Support\Devflow;

/**
 * DEVFLOW-1 — Sprint evidence generator.
 *
 * Assembles a structured evidence pack from REAL sources (manifest, git,
 * test plan, optional CI/deploy/smoke logs). Missing values are rendered as
 * NOT AVAILABLE — never invented. Sensitive labels are redacted.
 *
 * Read/compose only; writing the file is the command's responsibility so this
 * class stays unit-testable.
 */
final class SprintEvidenceGenerator
{
    private const NA = 'NOT AVAILABLE';

    public function __construct(private readonly GitChangeInspector $git) {}

    /**
     * @param  array<string,mixed>  $extra  optional real inputs: pr, ci, tests, migrations, backup, deploy, smoke, queue, logs, tag, decision, residual_risk, rollback
     * @return array<string,mixed>
     */
    public function build(SprintManifest $manifest, array $extra = []): array
    {
        $evidence = [
            'sprint_id' => $manifest->id() ?? self::NA,
            'type' => $manifest->type() ?? self::NA,
            'module' => $manifest->module() ?? self::NA,
            'branch' => $this->git->currentBranch() ?? self::NA,
            'base_branch' => $manifest->baseBranch() ?? self::NA,
            'commit' => $this->git->headCommit() ?? self::NA,
            'tag_at_head' => $this->git->tagAtHead() ?? self::NA,
            'generated_at_unix' => time(),
            'pr' => $extra['pr'] ?? self::NA,
            'ci' => $extra['ci'] ?? self::NA,
            'test_plan' => $extra['test_plan'] ?? self::NA,
            'test_results' => $extra['tests'] ?? self::NA,
            'graphify' => $extra['graphify'] ?? self::NA,
            'migrations' => $extra['migrations'] ?? self::NA,
            'backup' => $extra['backup'] ?? self::NA,
            'deploy' => $extra['deploy'] ?? self::NA,
            'smoke' => $extra['smoke'] ?? self::NA,
            'queue' => $extra['queue'] ?? self::NA,
            'logs' => $extra['logs'] ?? self::NA,
            'go_tag' => $manifest->goTag() ?? self::NA,
            'decision' => $extra['decision'] ?? self::NA,
            'residual_risk' => $extra['residual_risk'] ?? self::NA,
            'rollback' => $extra['rollback'] ?? self::NA,
        ];

        return $this->redact($evidence);
    }

    /**
     * @param  array<string,mixed>  $evidence
     */
    public function toMarkdown(array $evidence): string
    {
        $row = static function (string $label, mixed $value): string {
            $rendered = is_scalar($value) ? (string) $value : json_encode($value, JSON_UNESCAPED_SLASHES);

            return "| {$label} | {$rendered} |";
        };

        $lines = [
            '# Sprint Evidence — '.($evidence['sprint_id'] ?? self::NA),
            '',
            '| Field | Value |',
            '| --- | --- |',
            $row('Type', $evidence['type'] ?? self::NA),
            $row('Module', $evidence['module'] ?? self::NA),
            $row('Branch', $evidence['branch'] ?? self::NA),
            $row('Base branch', $evidence['base_branch'] ?? self::NA),
            $row('Commit', $evidence['commit'] ?? self::NA),
            $row('PR', $evidence['pr'] ?? self::NA),
            $row('CI', $evidence['ci'] ?? self::NA),
            $row('Test results', $evidence['test_results'] ?? self::NA),
            $row('Migrations', $evidence['migrations'] ?? self::NA),
            $row('Backup', $evidence['backup'] ?? self::NA),
            $row('Deploy', $evidence['deploy'] ?? self::NA),
            $row('Smoke', $evidence['smoke'] ?? self::NA),
            $row('Queue', $evidence['queue'] ?? self::NA),
            $row('GO tag', $evidence['go_tag'] ?? self::NA),
            $row('Decision', $evidence['decision'] ?? self::NA),
            $row('Residual risk', $evidence['residual_risk'] ?? self::NA),
            $row('Rollback', $evidence['rollback'] ?? self::NA),
            '',
            '_Generated by `php artisan sprint:evidence`. NOT AVAILABLE = evidence not yet produced._',
        ];

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  array<string,mixed>  $data
     * @return array<string,mixed>
     */
    private function redact(array $data): array
    {
        $labels = (array) config('devflow.evidence.redact_labels', []);

        foreach ($data as $key => $value) {
            $lowerKey = strtolower((string) $key);
            foreach ($labels as $label) {
                if (str_contains($lowerKey, (string) $label)) {
                    $data[$key] = '[REDACTED]';

                    continue 2;
                }
            }
            if (is_string($value)) {
                $data[$key] = $this->maskString($value, $labels);
            }
        }

        return $data;
    }

    /**
     * @param  list<string>  $labels
     */
    private function maskString(string $value, array $labels): string
    {
        // Mask long digit runs (KTP/NIK/phone-like) and obvious secret tokens.
        $value = (string) preg_replace('/\b\d{13,}\b/', '[REDACTED-DIGITS]', $value);

        foreach ($labels as $label) {
            $value = (string) preg_replace('/('.preg_quote((string) $label, '/').'\s*[:=]\s*)\S+/i', '$1[REDACTED]', $value);
        }

        return $value;
    }
}
