<?php

declare(strict_types=1);

namespace App\Modules\LegacyImport\MassUpload\Support;

/**
 * One clinical document safely extracted from a mass-upload archive.
 *
 * `logicalName` is the name the archive used and the key the manifest matches
 * against. `absolutePath` is a path THIS APPLICATION chose.
 *
 * Those two are deliberately decoupled, and that decoupling is the Zip Slip
 * defence. The archive's name never becomes a filesystem path, so a crafted
 * entry called `../../../../etc/cron.d/x` cannot escape anywhere — it can only
 * fail to match a manifest row. Sanitising a hostile name and then using it is
 * the weaker pattern: it depends on the sanitiser being perfect, whereas this
 * depends on nothing.
 */
final class LegacyMassUploadExtractedDocument
{
    public function __construct(
        /** Name as it appeared in the archive. A manifest key, never a path. */
        public readonly string $logicalName,

        /** Absolute path on the private workspace disk, generated by us. */
        public readonly string $absolutePath,

        /** Path relative to the workspace root, for staging/audit. */
        public readonly string $relativePath,

        public readonly int $bytes,

        public readonly string $sha256,
    ) {}
}
